(()=>{
'use strict';
if(window.__horticultureMessagingV1)return;window.__horticultureMessagingV1=true;
const API='https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec',USERS='horticulture-admin-users-v2',SESSION='horticulture-admin-session-v1',PERSIST='horticulture-admin-persistent-session-v1';
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let peer=null,timer=null;
function me(){try{return JSON.parse(localStorage.getItem(PERSIST)||sessionStorage.getItem(SESSION)||'null')}catch{return null}}
function users(){try{return JSON.parse(localStorage.getItem(USERS)||'[]').filter(x=>x.active!==false)}catch{return[]}}
function person(id){return users().find(x=>String(x.id)===String(id))||{id,name:'Membre'} }
function name(u){return [u.firstName,u.lastName].filter(Boolean).join(' ')||u.username||'Membre'}
function initials(u){return ((u.firstName?.[0]||'')+(u.lastName?.[0]||'')).toUpperCase()||'M'}
async function post(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)}),j=await r.json();if(!j?.ok)throw Error(j?.error||'Erreur messagerie');return j}
function ensure(){let v=$('#messaging');if(v)return v;v=document.createElement('section');v.id='messaging';v.className='view';document.querySelector('#appShell main.app')?.appendChild(v);return v}
const css=`<style>.msgTop{display:flex;align-items:center;gap:10px;margin-bottom:16px}.msgBack{border:0;background:transparent;color:#07583f;font-weight:850;font-size:15px;padding:8px}.msgTitle{font-size:28px;font-weight:900;color:#173126}.msgNew{margin-left:auto;width:42px;height:42px;border:0;border-radius:50%;background:#07583f;color:#fff;font-size:24px}.msgList{background:#fff;border:1px solid #e1e8e3;border-radius:20px;overflow:hidden}.msgRow{width:100%;display:flex;align-items:center;gap:12px;border:0;border-bottom:1px solid #edf1ee;background:#fff;padding:13px;text-align:left}.msgRow:last-child{border:0}.msgAvatar{width:50px;height:50px;border-radius:50%;display:grid;place-items:center;background:#e4f2e9;color:#07583f;font-weight:900;flex:0 0 auto}.msgMeta{min-width:0;flex:1}.msgMeta b{display:block;font-size:15px}.msgMeta span{display:block;color:#738079;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:3px}.msgTime{font-size:11px;color:#929b96}.msgChat{display:flex;flex-direction:column;height:calc(100vh - 185px);min-height:460px}.msgChatHead{display:flex;align-items:center;gap:9px;border-bottom:1px solid #e1e8e3;padding-bottom:10px}.msgChatHead .msgAvatar{width:38px;height:38px}.msgMessages{flex:1;overflow:auto;padding:18px 4px;display:flex;flex-direction:column;gap:7px}.msgBubble{max-width:78%;padding:10px 13px;border-radius:18px;background:#e9eeeb;align-self:flex-start;line-height:1.35;white-space:pre-wrap}.msgBubble.mine{background:#087452;color:#fff;align-self:flex-end}.msgBubble small{display:block;font-size:9px;opacity:.65;margin-top:4px;text-align:right}.msgComposer{display:flex;gap:8px;align-items:flex-end;border-top:1px solid #e1e8e3;padding:10px 0 calc(5px + env(safe-area-inset-bottom))}.msgComposer textarea{flex:1;resize:none;min-height:42px;max-height:100px;border:1px solid #d8e1dc;border-radius:20px;padding:10px 14px}.msgSend{width:42px;height:42px;border:0;border-radius:50%;background:#07583f;color:#fff;font-size:19px}.msgEmpty{text-align:center;color:#7a8780;padding:42px 15px}.msgPeople{display:grid;gap:8px}.msgPeople button{display:flex;align-items:center;gap:10px;border:1px solid #e1e8e3;background:#fff;border-radius:14px;padding:10px;text-align:left}</style>`;
function show(){document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='messaging'));$('#drawer')?.classList.remove('open');window.scrollTo(0,0)}
async function home(){peer=null;const v=ensure(),self=me();v.innerHTML=css+`<div class="msgTop"><button class="msgBack">← Accueil</button><div class="msgTitle">Messages</div><button class="msgNew" title="Nouveau message">＋</button></div><div class="msgList"><div class="msgEmpty">Chargement des conversations…</div></div>`;show();$('.msgBack',v).onclick=openHome;$('.msgNew',v).onclick=choose;try{const j=await post({action:'listInternalConversations',userId:self?.id||''});const list=j.conversations||[];$('.msgList',v).innerHTML=list.length?list.map(c=>{const other=person(c.otherUserId);return `<button class="msgRow" data-peer="${esc(c.otherUserId)}"><span class="msgAvatar">${esc(initials(other))}</span><span class="msgMeta"><b>${esc(name(other))}</b><span>${esc(c.lastMessage||'Nouvelle conversation')}</span></span><span class="msgTime">${c.updatedAt?new Date(c.updatedAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):''}</span></button>`}).join(''):'<div class="msgEmpty">Aucune conversation.<br>Appuyez sur ＋ pour écrire à un membre.</div>';v.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.peer))}catch(e){$('.msgList',v).innerHTML=`<div class="msgEmpty">${esc(e.message)}</div>`}}
function choose(){const v=ensure(),self=me(),list=users().filter(x=>String(x.id)!==String(self?.id));v.innerHTML=css+`<div class="msgTop"><button class="msgBack">← Messages</button><div class="msgTitle">Nouveau message</div></div><div class="msgPeople">${list.map(u=>`<button data-peer="${esc(u.id)}"><span class="msgAvatar">${esc(initials(u))}</span><b>${esc(name(u))}</b></button>`).join('')}</div>`;$('.msgBack',v).onclick=home;v.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.peer))}
async function chat(id){peer=String(id);const v=ensure(),self=me(),u=person(peer);v.innerHTML=css+`<div class="msgChat"><div class="msgChatHead"><button class="msgBack">←</button><span class="msgAvatar">${esc(initials(u))}</span><b>${esc(name(u))}</b></div><div class="msgMessages"><div class="msgEmpty">Chargement…</div></div><div class="msgComposer"><textarea placeholder="Message" rows="1"></textarea><button class="msgSend">↑</button></div></div>`;show();$('.msgBack',v).onclick=home;$('.msgSend',v).onclick=send;$('.msgComposer textarea',v).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});await refreshChat()}
async function refreshChat(){if(!peer)return;const self=me(),box=$('#messaging .msgMessages');if(!box)return;try{const j=await post({action:'listInternalMessages',userId:self?.id||'',peerId:peer});box.innerHTML=(j.messages||[]).map(m=>`<div class="msgBubble ${String(m.senderId)===String(self?.id)?'mine':''}">${esc(m.text)}<small>${new Date(m.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="msgEmpty">Écrivez le premier message.</div>';box.scrollTop=box.scrollHeight}catch(e){box.innerHTML=`<div class="msgEmpty">${esc(e.message)}</div>`}}
async function send(){const self=me(),input=$('#messaging .msgComposer textarea'),text=input?.value.trim();if(!text||!peer)return;input.value='';try{await post({action:'sendInternalMessage',userId:self?.id||'',recipientId:peer,text});await refreshChat()}catch(e){alert('Message non envoyé : '+e.message)}}
function openHome(){peer=null;document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='home'));window.scrollTo(0,0)}
function wire(){const grid=$('#home .grid,#home .dashGrid');if(grid&&!grid.querySelector('[data-module="messaging"]')){const b=document.createElement('button');b.className=grid.classList.contains('dashGrid')?'dashTile':'space';b.dataset.module='messaging';b.innerHTML='<span class="ico">💬</span><b>Messagerie</b><small>Messages internes de l’association</small>';grid.appendChild(b)}document.querySelectorAll('[data-module="messaging"]').forEach(b=>b.onclick=e=>{e.preventDefault();home()})}
wire();setInterval(()=>{wire();if(peer)refreshChat()},5000);window.addEventListener('horticulture-users-synced',wire);window.HorticultureMessaging={open:home};
})();