(()=>{
'use strict';
if(window.__horticultureMessagingV6)return;window.__horticultureMessagingV6=true;
const API='https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec';
const USERS='horticulture-admin-users-v2',SESSION='horticulture-admin-session-v1',PERSIST='horticulture-admin-persistent-session-v1';
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let peer=null,conversations=[],filter='all';
const I={back:'<svg viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',msg:'<svg viewBox="0 0 24 24"><path d="M5 5.5h10a4 4 0 0 1 4 4v2a4 4 0 0 1-4 4h-5l-5 3 .8-3H5a4 4 0 0 1-4-4v-2a4 4 0 0 1 4-4Z"/><path d="M7 10h7M7 13h4"/></svg>',send:'<svg viewBox="0 0 24 24"><path d="m4 5 16 7-16 7 3-7-3-7Z"/><path d="M7 12h13"/></svg>',clip:'<svg viewBox="0 0 24 24"><path d="m8 12 5-5a3 3 0 0 1 4 4l-7 7a5 5 0 0 1-7-7l7-7"/></svg>',info:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 10v6"/><circle cx="12" cy="7" r="1"/></svg>'};
function me(){try{return JSON.parse(localStorage.getItem(PERSIST)||sessionStorage.getItem(SESSION)||'null')}catch{return null}}
function users(){try{return JSON.parse(localStorage.getItem(USERS)||'[]').filter(x=>x.active!==false)}catch{return[]}}
function person(id){return users().find(x=>String(x.id)===String(id))||{id,firstName:'Membre'}}
function name(u){return [u.firstName,u.lastName].filter(Boolean).join(' ')||u.username||'Membre'}
function initials(u){return ((u.firstName?.[0]||'')+(u.lastName?.[0]||'')).toUpperCase()||'M'}
function avatar(u,cls=''){return u?.photo?`<span class="m6Avatar ${cls}"><img src="${esc(u.photo)}" alt=""></span>`:`<span class="m6Avatar ${cls}">${esc(initials(u))}</span>`}
function when(v){if(!v)return'';const d=new Date(v),n=new Date();if(d.toDateString()===n.toDateString())return d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});const y=new Date(n);y.setDate(n.getDate()-1);if(d.toDateString()===y.toDateString())return'Hier';return d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','')}
async function post(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});let j=null;try{j=await r.json()}catch{}if(!j?.ok)throw Error(j?.error||'Erreur messagerie');return j}
function ensure(){let v=$('#messaging');if(v)return v;v=document.createElement('section');v.id='messaging';v.className='view';document.querySelector('#appShell main.app')?.appendChild(v);return v}
const css=`<style>
#messaging{--g:#07583f;--gd:#063d2f;--line:#dfe6e1;--mut:#77837c;--soft:#f4f7f5;color:#173126}
#messaging svg{width:100%;height:100%;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
.m6Shell{background:#fff;border:1px solid var(--line);border-radius:22px;overflow:hidden;min-height:660px;box-shadow:0 14px 34px #0a3d2c0d}.m6Layout{display:grid;grid-template-columns:350px minmax(0,1fr);min-height:660px}.m6Side{background:#fff;border-right:1px solid var(--line)}
.m6Head{background:linear-gradient(135deg,var(--g),var(--gd));color:#fff;padding:15px 15px 13px}.m6HeadTop{display:flex;align-items:center;gap:10px}.m6Home,.m6BackList{width:40px;height:40px;border:0;border-radius:12px;background:#ffffff14;color:#fff;padding:9px}.m6Title{font-size:24px;font-weight:900;flex:1;letter-spacing:-.02em}.m6New{width:42px;height:42px;border:0;border-radius:50%;background:#fff;color:var(--g);padding:10px}.m6Tabs{display:flex;gap:7px;margin-top:13px;overflow:auto}.m6Tab{border:0;border-radius:999px;background:#ffffff16;color:#ecf6f1;padding:7px 12px;font-size:12px;font-weight:800;white-space:nowrap}.m6Tab.active{background:#fff;color:var(--g)}
.m6SearchWrap{padding:11px 12px 9px}.m6Search{position:relative}.m6Search span{position:absolute;left:13px;top:11px;width:18px;height:18px;color:#89948e}.m6Search input{width:100%;height:44px;border:1px solid var(--line);border-radius:14px;background:#f6f8f7;padding:0 13px 0 42px;outline:none}.m6Search input:focus{background:#fff;border-color:#9ec8b0;box-shadow:0 0 0 3px #e9f4ed}
.m6List{border-top:1px solid #edf1ee}.m6Row{width:100%;display:flex;align-items:center;gap:12px;border:0;border-bottom:1px solid #edf1ee;background:#fff;padding:13px 12px;text-align:left}.m6Row:hover,.m6Row.active{background:#f0f7f3}.m6Avatar{width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#dff0e5,#b6dcc4);color:var(--g);font-weight:900;overflow:hidden;flex:0 0 auto}.m6Avatar.small{width:42px;height:42px}.m6Avatar.big{width:92px;height:92px;font-size:26px}.m6Avatar img{width:100%;height:100%;object-fit:cover}.m6Meta{min-width:0;flex:1}.m6Meta b{display:block;font-size:14px}.m6Preview{display:block;color:#75817b;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:3px}.m6Right{display:grid;justify-items:end;gap:5px}.m6Time{font-size:10px;color:#919a95}.m6Unread{min-width:21px;height:21px;padding:0 6px;border-radius:999px;background:#1c9d5b;color:#fff;font-size:10px;font-weight:900;display:grid;place-items:center}
.m6Empty{padding:38px 20px 28px;text-align:center}.m6EmptyCard{max-width:300px;margin:auto;background:#f7faf8;border:1px solid #e3ebe6;border-radius:20px;padding:24px 20px}.m6EmptyIcon{width:62px;height:62px;border-radius:50%;background:#e9f4ed;color:var(--g);display:grid;place-items:center;padding:16px;margin:0 auto 13px}.m6EmptyCard b{display:block;font-size:17px}.m6EmptyCard p{margin:6px 0 16px;color:var(--mut);font-size:13px;line-height:1.45}.m6Start{border:0;border-radius:13px;background:var(--g);color:#fff;font-weight:850;padding:11px 16px}
.m6Main{min-width:0;background:#f1f4f0}.m6Welcome{height:100%;display:grid;place-items:center;text-align:center;color:#77837c}.m6WelcomeCard{background:#fff;border:1px solid var(--line);border-radius:20px;padding:24px;max-width:300px}.m6WelcomeCard span{display:grid;width:64px;height:64px;border-radius:50%;background:#e9f4ed;color:var(--g);padding:16px;margin:0 auto 13px}
.m6Chat{height:660px;display:flex;flex-direction:column}.m6ChatHead{height:66px;background:linear-gradient(135deg,var(--g),var(--gd));color:#fff;display:flex;align-items:center;gap:10px;padding:0 10px}.m6BackList{display:none;background:transparent}.m6Peer{min-width:0;flex:1}.m6Peer b{display:block;font-size:15px}.m6Peer small{display:block;color:#d7ebe0;font-size:11px;margin-top:2px}.m6HeadBtn{width:38px;height:38px;border:0;background:transparent;color:#fff;padding:9px}.m6Messages{flex:1;overflow:auto;padding:18px 13px;display:flex;flex-direction:column;gap:8px;background:#edf1eb;background-image:radial-gradient(#07583f0a 1px,transparent 1px);background-size:18px 18px}.m6Day{align-self:center;background:#e0e6e1;color:#67736c;border-radius:10px;padding:5px 9px;font-size:10px;margin:2px 0 5px}.m6Bubble{max-width:72%;padding:9px 11px;border-radius:10px 10px 10px 3px;background:#fff;align-self:flex-start;box-shadow:0 2px 7px #0000000d;line-height:1.42;white-space:pre-wrap}.m6Bubble.mine{background:#d9f4d6;align-self:flex-end;border-radius:10px 10px 3px 10px}.m6Bubble small{display:block;text-align:right;color:#708078;font-size:9px;margin-top:4px}.m6Checks{color:#2383b8;font-weight:900;margin-left:3px}.m6Composer{display:flex;align-items:flex-end;gap:7px;padding:9px 10px calc(9px + env(safe-area-inset-bottom));background:#eef1ef;border-top:1px solid #dce3de}.m6Attach{width:40px;height:40px;border:0;background:#fff;border-radius:50%;color:#74817a;padding:10px}.m6Composer textarea{flex:1;resize:none;min-height:42px;max-height:105px;border:0;border-radius:22px;background:#fff;padding:11px 14px;outline:none}.m6Send{width:42px;height:42px;border:0;border-radius:50%;background:#168f55;color:#fff;padding:11px}
.m6People{display:grid;gap:8px;padding:14px;background:#f5f7f5}.m6People button{display:flex;align-items:center;gap:11px;border:1px solid var(--line);background:#fff;border-radius:14px;padding:10px;text-align:left}.m6PeopleTitle{padding:14px 14px 6px;font-weight:900;color:var(--gd)}
.m6Info{height:660px;overflow:auto;background:#f4f7f5;padding:14px}.m6InfoTop{display:flex;align-items:center;gap:8px;margin-bottom:12px}.m6InfoBack{width:40px;height:40px;border:0;border-radius:12px;background:#fff;color:var(--g);padding:9px}.m6InfoCard{background:#fff;border:1px solid var(--line);border-radius:18px;padding:16px;margin-bottom:11px}.m6Profile{text-align:center}.m6Profile .m6Avatar{margin:auto}.m6Profile h2{margin:10px 0 3px}.m6Profile p{margin:0;color:#7b8781;font-size:12px}.m6InfoRow{display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #edf1ee;font-size:13px}.m6InfoRow:last-child{border-bottom:0}
@media(max-width:700px){#messaging{margin:-20px -16px -100px}.m6Shell{border:0;border-radius:0;box-shadow:none;min-height:calc(100vh - 72px)}.m6Layout{display:block;min-height:0}.m6Side{border:0}.m6Main{display:none}.m6Head{padding:13px 14px 12px}.m6Title{font-size:24px}.m6SearchWrap{padding:10px 12px 8px}.m6Tabs{gap:6px}.m6Tab{padding:7px 11px}.m6Layout.chatOpen .m6Side{display:none}.m6Layout.chatOpen .m6Main{display:block}.m6Chat,.m6Info{height:calc(100vh - 72px);min-height:500px}.m6BackList{display:block}.m6Bubble{max-width:84%}.m6Messages{padding:16px 10px}.m6Empty{padding-top:28px}.bottom{display:none!important}}
</style>`;
function show(){document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='messaging'));$('#drawer')?.classList.remove('open');window.scrollTo(0,0)}
function shell(){const v=ensure();v.innerHTML=css+`<div class="m6Shell"><div class="m6Layout"><aside class="m6Side"><div class="m6Head"><div class="m6HeadTop"><button class="m6Home" title="Retour">${I.back}</button><div class="m6Title">Messagerie</div><button class="m6New" title="Nouveau message">${I.plus}</button></div><div class="m6Tabs"><button class="m6Tab active" data-filter="all">Toutes</button><button class="m6Tab" data-filter="unread">Non lus</button><button class="m6Tab" data-filter="groups">Groupes</button><button class="m6Tab" data-filter="archive">Archives</button></div></div><div class="m6SearchWrap"><div class="m6Search"><span>${I.search}</span><input placeholder="Rechercher une conversation…"></div></div><div class="m6List"></div></aside><main class="m6Main"><div class="m6Welcome"><div class="m6WelcomeCard"><span>${I.msg}</span><b>Messagerie interne</b><div style="margin-top:6px">Sélectionnez une conversation.</div></div></div></main></div></div>`;show();$('.m6Home',v).onclick=openHome;$('.m6New',v).onclick=choose;$('.m6Search input',v).oninput=e=>draw(e.target.value);v.querySelectorAll('.m6Tab').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;v.querySelectorAll('.m6Tab').forEach(x=>x.classList.toggle('active',x===b));draw($('.m6Search input',v)?.value||'')});draw('')}
function emptyHtml(text='Aucune conversation.',cta=true){return `<div class="m6Empty"><div class="m6EmptyCard"><div class="m6EmptyIcon">${I.msg}</div><b>${esc(text)}</b><p>${cta?'Commencez une discussion avec un membre de l’association.':'Aucun élément à afficher ici.'}</p>${cta?'<button class="m6Start">Nouveau message</button>':''}</div></div>`}
async function home(){peer=null;filter='all';shell();try{const j=await post({action:'listInternalConversations',userId:me()?.id||''});conversations=j.conversations||[];draw('')}catch(e){conversations=[];draw('');const box=$('.m6List',ensure());if(String(e.message||'').includes('Action inconnue')){box.innerHTML=emptyHtml('Messagerie en cours d’activation.',true);box.querySelector('.m6Start')?.addEventListener('click',choose)}else{box.innerHTML=emptyHtml('Impossible de charger les conversations.',true);box.querySelector('.m6Start')?.addEventListener('click',choose)}}}
function draw(q=''){const v=ensure(),needle=String(q||'').trim().toLowerCase();let list=conversations.filter(c=>{const u=person(c.otherUserId);return !needle||name(u).toLowerCase().includes(needle)||String(c.lastMessage||'').toLowerCase().includes(needle)});if(filter==='unread')list=list.filter(c=>Number(c.unread)>0);if(filter==='groups'||filter==='archive')list=[];const box=$('.m6List',v);if(!box)return;if(!list.length){box.innerHTML=filter==='groups'?emptyHtml('Aucun groupe.',false):filter==='archive'?emptyHtml('Aucune archive.',false):needle?emptyHtml('Aucun résultat.',false):emptyHtml('Aucune conversation.',true);box.querySelector('.m6Start')?.addEventListener('click',choose);return}box.innerHTML=list.map(c=>{const u=person(c.otherUserId);return `<button class="m6Row ${String(peer)===String(c.otherUserId)?'active':''}" data-peer="${esc(c.otherUserId)}">${avatar(u)}<span class="m6Meta"><b>${esc(name(u))}</b><span class="m6Preview">${esc(c.lastMessage||'Nouvelle conversation')}</span></span><span class="m6Right"><span class="m6Time">${esc(when(c.updatedAt))}</span>${Number(c.unread)>0?`<span class="m6Unread">${Number(c.unread)>99?'99+':Number(c.unread)}</span>`:''}</span></button>`}).join('');v.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.peer))}
function choose(){const v=ensure(),list=users().filter(x=>String(x.id)!==String(me()?.id));$('.m6Main',v).innerHTML=`<div class="m6Chat"><div class="m6ChatHead"><button class="m6BackList">${I.back}</button><b>Nouveau message</b></div><div class="m6PeopleTitle">Choisir un membre</div><div class="m6People">${list.map(u=>`<button data-new-peer="${esc(u.id)}">${avatar(u,'small')}<b>${esc(name(u))}</b></button>`).join('')||'<div class="m6Empty">Aucun autre membre disponible.</div>'}</div></div>`;$('.m6Layout',v).classList.add('chatOpen');$('.m6BackList',v)?.addEventListener('click',()=>$('.m6Layout',v).classList.remove('chatOpen'));v.querySelectorAll('[data-new-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.newPeer))}
async function chat(id){peer=String(id);const v=ensure(),u=person(peer);draw($('.m6Search input',v)?.value||'');$('.m6Main',v).innerHTML=`<div class="m6Chat"><div class="m6ChatHead"><button class="m6BackList">${I.back}</button>${avatar(u,'small')}<span class="m6Peer"><b>${esc(name(u))}</b><small>Conversation interne</small></span><button class="m6HeadBtn" title="Informations">${I.info}</button></div><div class="m6Messages"><div class="m6Day">Aujourd’hui</div><div class="m6Empty">Chargement…</div></div><div class="m6Composer"><button class="m6Attach" title="Pièce jointe">${I.clip}</button><textarea placeholder="Écrire un message…" rows="1"></textarea><button class="m6Send" title="Envoyer">${I.send}</button></div></div>`;$('.m6Layout',v).classList.add('chatOpen');$('.m6BackList',v).onclick=()=>{peer=null;$('.m6Layout',v).classList.remove('chatOpen');draw($('.m6Search input',v)?.value||'')};$('.m6HeadBtn',v).onclick=()=>info(u);$('.m6Send',v).onclick=send;$('.m6Composer textarea',v).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});await refreshChat()}
async function refreshChat(){if(!peer)return;const self=me(),box=$('#messaging .m6Messages');if(!box)return;try{const j=await post({action:'listInternalMessages',userId:self?.id||'',peerId:peer});const rows=j.messages||[];box.innerHTML='<div class="m6Day">Aujourd’hui</div>'+((rows.length)?rows.map(m=>`<div class="m6Bubble ${String(m.senderId)===String(self?.id)?'mine':''}">${esc(m.text)}<small>${new Date(m.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}${String(m.senderId)===String(self?.id)?'<span class="m6Checks">✓✓</span>':''}</small></div>`).join(''):'<div class="m6Empty">Écrivez le premier message.</div>');box.scrollTop=box.scrollHeight}catch(e){box.innerHTML='<div class="m6Day">Aujourd’hui</div><div class="m6Empty">Impossible de charger cette conversation.</div>'}}
async function send(){const self=me(),input=$('#messaging .m6Composer textarea'),text=input?.value.trim();if(!text||!peer)return;input.value='';try{await post({action:'sendInternalMessage',userId:self?.id||'',recipientId:peer,text});await refreshChat();const j=await post({action:'listInternalConversations',userId:self?.id||''});conversations=j.conversations||[];draw($('.m6Search input',ensure())?.value||'')}catch(e){alert('Message non envoyé : '+(e?.message||'erreur'))}}
function info(u){const v=ensure();$('.m6Main',v).innerHTML=`<div class="m6Info"><div class="m6InfoTop"><button class="m6InfoBack">${I.back}</button><b>Infos du contact</b></div><div class="m6InfoCard m6Profile">${avatar(u,'big')}<h2>${esc(name(u))}</h2><p>${esc(u.function||u.role||'Membre de l’association')}</p></div><div class="m6InfoCard"><div class="m6InfoRow"><span>E-mail</span><b>${esc(u.email||'Non renseigné')}</b></div><div class="m6InfoRow"><span>Téléphone</span><b>${esc(u.phone||'Non renseigné')}</b></div></div></div>`;$('.m6InfoBack',v).onclick=()=>chat(peer)}
function openHome(){peer=null;document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='home'));document.body.classList.remove('messaging-open');window.scrollTo(0,0)}
function tile(){const grid=$('#home .grid,#home .dashGrid');if(!grid)return;let b=grid.querySelector('[data-module="messaging"]');if(!b){b=document.createElement('button');b.className=grid.classList.contains('dashGrid')?'dashTile':'space';b.dataset.module='messaging';b.innerHTML=`<span class="ico" style="padding:10px">${I.msg}</span><b>Messagerie</b><small>Messages internes de l’association</small>`;const adh=grid.querySelector('[data-permission="adherents"]');const comp=grid.querySelector('[data-permission="comptabilite"]');if(adh&&comp)grid.insertBefore(b,comp);else grid.appendChild(b)}else{const i=b.querySelector('.ico');if(i)i.innerHTML=I.msg}b.onclick=e=>{e.preventDefault();document.body.classList.add('messaging-open');home()}}
tile();setInterval(()=>{tile();if(peer)refreshChat()},5000);window.addEventListener('horticulture-users-synced',tile);window.HorticultureMessaging={open:home};
})();