(()=>{
'use strict';
if(window.__horticultureMessagingV5)return;window.__horticultureMessagingV5=true;
const API='https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec';
const USERS='horticulture-admin-users-v2',SESSION='horticulture-admin-session-v1',PERSIST='horticulture-admin-persistent-session-v1';
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let peer=null,conversations=[],filter='all';
const I={
 back:'<svg viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg>',
 search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>',
 msg:'<svg viewBox="0 0 24 24"><path d="M4 5h12a4 4 0 0 1 4 4v3a4 4 0 0 1-4 4h-5l-5 3 .8-3H4a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3Z"/><path d="M7 9h7M7 12h5"/></svg>',
 plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
 send:'<svg viewBox="0 0 24 24"><path d="m4 5 16 7-16 7 3-7-3-7Z"/><path d="M7 12h13"/></svg>',
 clip:'<svg viewBox="0 0 24 24"><path d="m8 12 5-5a3 3 0 0 1 4 4l-7 7a5 5 0 0 1-7-7l7-7"/></svg>',
 info:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 10v6"/><circle cx="12" cy="7" r="1"/></svg>',
 call:'<svg viewBox="0 0 24 24"><path d="M5 4l3 4-2 2c2 4 4 6 8 8l2-2 4 3c-1 2-2 3-5 3C8 20 4 16 2 9c0-3 1-4 3-5Z"/></svg>'
};
function me(){try{return JSON.parse(localStorage.getItem(PERSIST)||sessionStorage.getItem(SESSION)||'null')}catch{return null}}
function users(){try{return JSON.parse(localStorage.getItem(USERS)||'[]').filter(x=>x.active!==false)}catch{return[]}}
function person(id){return users().find(x=>String(x.id)===String(id))||{id,firstName:'Membre'}}
function name(u){return [u.firstName,u.lastName].filter(Boolean).join(' ')||u.username||'Membre'}
function initials(u){return ((u.firstName?.[0]||'')+(u.lastName?.[0]||'')).toUpperCase()||'M'}
function avatar(u,cls=''){return u?.photo?`<span class="wmAvatar ${cls}"><img src="${esc(u.photo)}" alt=""></span>`:`<span class="wmAvatar ${cls}">${esc(initials(u))}</span>`}
function when(v){if(!v)return'';const d=new Date(v),n=new Date();if(d.toDateString()===n.toDateString())return d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});const y=new Date(n);y.setDate(n.getDate()-1);if(d.toDateString()===y.toDateString())return'Hier';return d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','')}
async function post(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});let j=null;try{j=await r.json()}catch{}if(!j?.ok)throw Error(j?.error||'Erreur messagerie');return j}
function ensure(){let v=$('#messaging');if(v)return v;v=document.createElement('section');v.id='messaging';v.className='view';document.querySelector('#appShell main.app')?.appendChild(v);return v}
const css=`<style>
#messaging{--wm-green:#07583f;--wm-deep:#063d2f;--wm-line:#e2e8e4;--wm-muted:#78837d;--wm-bg:#f4f7f5;color:#173126}
#messaging svg{width:100%;height:100%;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
.wmShell{background:#fff;border:1px solid var(--wm-line);border-radius:22px;overflow:hidden;box-shadow:0 14px 34px #0a3d2c0d;min-height:650px}.wmLayout{display:grid;grid-template-columns:340px minmax(0,1fr);min-height:650px}.wmSide{background:#fff;border-right:1px solid var(--wm-line)}
.wmHeader{background:linear-gradient(135deg,var(--wm-green),var(--wm-deep));color:#fff;padding:18px 16px 16px}.wmHeaderTop{display:flex;align-items:center;gap:10px}.wmHome{width:38px;height:38px;border:0;background:#ffffff14;color:#fff;border-radius:11px;padding:8px}.wmTitle{font-size:23px;font-weight:900;flex:1;letter-spacing:-.02em}.wmNew{width:40px;height:40px;border:0;border-radius:50%;background:#fff;color:var(--wm-green);padding:9px}.wmTabs{display:flex;gap:7px;margin-top:14px;overflow:auto;padding-bottom:1px}.wmTab{border:0;border-radius:999px;padding:7px 12px;background:#ffffff18;color:#eaf5ef;font-size:12px;font-weight:750;white-space:nowrap}.wmTab.active{background:#fff;color:var(--wm-green)}
.wmSearchWrap{padding:12px 13px;background:#fff}.wmSearch{position:relative}.wmSearch span{position:absolute;left:13px;top:11px;width:18px;height:18px;color:#8a958f}.wmSearch input{width:100%;height:43px;border:1px solid #dbe3de;border-radius:13px;background:#f5f8f6;padding:0 12px 0 41px;outline:none}.wmSearch input:focus{background:#fff;border-color:#a9cdb8;box-shadow:0 0 0 3px #e9f4ed}
.wmList{border-top:1px solid #edf1ee}.wmRow{width:100%;display:flex;align-items:center;gap:12px;border:0;border-bottom:1px solid #edf1ee;background:#fff;padding:12px 13px;text-align:left}.wmRow:hover,.wmRow.active{background:#f1f7f3}.wmAvatar{width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#dff0e5,#b8ddc6);color:var(--wm-green);font-weight:900;overflow:hidden;flex:0 0 auto}.wmAvatar.small{width:42px;height:42px}.wmAvatar.big{width:94px;height:94px;font-size:27px}.wmAvatar img{width:100%;height:100%;object-fit:cover}.wmMeta{min-width:0;flex:1}.wmMeta b{display:block;font-size:14px}.wmPreview{display:block;color:#75827b;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:3px}.wmRight{display:grid;justify-items:end;gap:5px}.wmTime{font-size:10px;color:#919a95}.wmUnread{min-width:20px;height:20px;padding:0 6px;border-radius:999px;background:#1f9d5c;color:#fff;font-size:10px;font-weight:900;display:grid;place-items:center}.wmEmpty{padding:46px 18px;text-align:center;color:#7d8982;line-height:1.5}.wmEmptyIcon{width:58px;height:58px;border-radius:50%;background:#edf5f0;color:var(--wm-green);display:grid;place-items:center;padding:15px;margin:0 auto 12px}
.wmMain{min-width:0;background:#f2f5f2}.wmWelcome{height:100%;display:grid;place-items:center;text-align:center;color:#77837c}.wmWelcomeCard{background:#fff;border:1px solid var(--wm-line);border-radius:20px;padding:26px 24px;max-width:300px}.wmWelcomeCard span{display:grid;width:66px;height:66px;border-radius:50%;background:#e8f3eb;color:var(--wm-green);padding:16px;margin:0 auto 13px}.wmWelcomeCard b{display:block;color:#173126;font-size:17px}
.wmChat{height:650px;display:flex;flex-direction:column}.wmChatHead{height:68px;background:linear-gradient(135deg,var(--wm-green),var(--wm-deep));color:#fff;display:flex;align-items:center;gap:10px;padding:0 12px}.wmBackList{display:none;width:38px;height:38px;border:0;background:transparent;color:#fff;padding:8px}.wmPeer{min-width:0;flex:1}.wmPeer b{display:block;font-size:15px}.wmPeer small{display:block;color:#d8ebe1;font-size:11px;margin-top:2px}.wmHeadAction{width:38px;height:38px;border:0;background:transparent;color:#fff;padding:9px}.wmMessages{flex:1;overflow:auto;padding:20px 14px;display:flex;flex-direction:column;gap:8px;background-color:#eef2ed;background-image:radial-gradient(#07583f0a 1px,transparent 1px);background-size:18px 18px}.wmDay{align-self:center;background:#e1e7e2;color:#657169;border-radius:10px;padding:5px 9px;font-size:10px;margin-bottom:4px}.wmBubble{max-width:72%;padding:9px 11px;border-radius:10px 10px 10px 3px;background:#fff;align-self:flex-start;box-shadow:0 2px 7px #0000000d;line-height:1.42;white-space:pre-wrap}.wmBubble.mine{background:#d9f5d7;align-self:flex-end;border-radius:10px 10px 3px 10px}.wmBubble small{display:block;text-align:right;color:#708078;font-size:9px;margin-top:4px}.wmChecks{color:#2383b8;font-weight:900;margin-left:3px}.wmComposer{display:flex;align-items:flex-end;gap:7px;padding:9px 10px calc(9px + env(safe-area-inset-bottom));background:#eef1ef;border-top:1px solid #dce3de}.wmAttach{width:40px;height:40px;border:0;background:#fff;border-radius:50%;color:#74817a;padding:10px}.wmComposer textarea{flex:1;resize:none;min-height:42px;max-height:105px;border:0;border-radius:22px;background:#fff;padding:11px 14px;outline:none}.wmSend{width:42px;height:42px;border:0;border-radius:50%;background:#168f55;color:#fff;padding:11px}
.wmPeople{display:grid;gap:8px;padding:14px;background:#f5f7f5}.wmPeople button{display:flex;align-items:center;gap:11px;border:1px solid var(--wm-line);background:#fff;border-radius:14px;padding:10px;text-align:left}.wmInfo{height:650px;overflow:auto;background:#f4f7f5;padding:16px}.wmInfoTop{display:flex;align-items:center;gap:8px;margin-bottom:12px}.wmInfoBack{width:38px;height:38px;border:0;background:#fff;color:var(--wm-green);border-radius:11px;padding:8px}.wmInfoCard{background:#fff;border:1px solid var(--wm-line);border-radius:18px;padding:16px;margin-bottom:11px}.wmProfile{text-align:center}.wmProfile .wmAvatar{margin:auto}.wmProfile h2{margin:10px 0 3px}.wmProfile p{margin:0;color:#7b8781;font-size:12px}.wmInfoActions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:15px}.wmInfoActions button{border:1px solid var(--wm-line);background:#fff;border-radius:13px;padding:11px 6px;color:var(--wm-green);font-weight:800;font-size:11px}.wmInfoRow{display:flex;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #edf1ee;font-size:13px}.wmInfoRow:last-child{border-bottom:0}
@media(max-width:700px){#messaging{margin:-20px -16px -100px}.wmShell{border:0;border-radius:0;box-shadow:none;min-height:calc(100vh - 72px)}.wmLayout{display:block;min-height:0}.wmSide{border:0}.wmMain{display:none}.wmHeader{padding:14px 16px 13px}.wmTitle{font-size:24px}.wmSearchWrap{padding:10px 12px}.wmList{border-top:0}.wmLayout.chatOpen .wmSide{display:none}.wmLayout.chatOpen .wmMain{display:block}.wmChat,.wmInfo{height:calc(100vh - 72px);min-height:500px}.wmBackList{display:block}.wmBubble{max-width:84%}.wmChatHead{height:64px;padding:0 7px}.wmMessages{padding:17px 10px}.wmInfo{padding:10px}.wmEmpty{padding-top:70px}.bottom{display:none!important}}
</style>`;
function show(){document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='messaging'));$('#drawer')?.classList.remove('open');window.scrollTo(0,0)}
function shell(){const v=ensure();v.innerHTML=css+`<div class="wmShell"><div class="wmLayout"><aside class="wmSide"><div class="wmHeader"><div class="wmHeaderTop"><button class="wmHome" title="Retour">${I.back}</button><div class="wmTitle">Messagerie</div><button class="wmNew" title="Nouveau message">${I.plus}</button></div><div class="wmTabs"><button class="wmTab active" data-filter="all">Toutes</button><button class="wmTab" data-filter="unread">Non lus</button><button class="wmTab" data-filter="groups">Groupes</button><button class="wmTab" data-filter="archive">Archives</button></div></div><div class="wmSearchWrap"><div class="wmSearch"><span>${I.search}</span><input placeholder="Rechercher une conversation…"></div></div><div class="wmList"><div class="wmEmpty"><div class="wmEmptyIcon">${I.msg}</div>Chargement des conversations…</div></div></aside><main class="wmMain"><div class="wmWelcome"><div class="wmWelcomeCard"><span>${I.msg}</span><b>Messagerie interne</b><div style="margin-top:6px">Sélectionnez une conversation.</div></div></div></main></div></div>`;show();$('.wmHome',v).onclick=openHome;$('.wmNew',v).onclick=choose;$('.wmSearch input',v).oninput=e=>draw(e.target.value);v.querySelectorAll('.wmTab').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;v.querySelectorAll('.wmTab').forEach(x=>x.classList.toggle('active',x===b));draw($('.wmSearch input',v)?.value||'')})}
async function home(){peer=null;filter='all';shell();try{const j=await post({action:'listInternalConversations',userId:me()?.id||''});conversations=j.conversations||[];draw('')}catch(e){$('.wmList',ensure()).innerHTML=`<div class="wmEmpty"><div class="wmEmptyIcon">${I.msg}</div>${esc(e.message)}</div>`}}
function draw(q=''){const v=ensure(),needle=String(q||'').trim().toLowerCase();let list=conversations.filter(c=>{const u=person(c.otherUserId);return !needle||name(u).toLowerCase().includes(needle)||String(c.lastMessage||'').toLowerCase().includes(needle)});if(filter==='unread')list=list.filter(c=>Number(c.unread)>0);if(filter==='groups'||filter==='archive')list=[];$('.wmList',v).innerHTML=list.length?list.map(c=>{const u=person(c.otherUserId);return `<button class="wmRow ${String(peer)===String(c.otherUserId)?'active':''}" data-peer="${esc(c.otherUserId)}">${avatar(u)}<span class="wmMeta"><b>${esc(name(u))}</b><span class="wmPreview">${esc(c.lastMessage||'Nouvelle conversation')}</span></span><span class="wmRight"><span class="wmTime">${esc(when(c.updatedAt))}</span>${Number(c.unread)>0?`<span class="wmUnread">${Number(c.unread)>99?'99+':Number(c.unread)}</span>`:''}</span></button>`}).join(''):`<div class="wmEmpty"><div class="wmEmptyIcon">${I.msg}</div>${filter==='groups'?'Aucun groupe pour le moment.':filter==='archive'?'Aucune conversation archivée.':needle?'Aucune conversation trouvée.':'Aucune conversation pour le moment.'}</div>`;v.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.peer))}
function choose(){const v=ensure(),list=users().filter(x=>String(x.id)!==String(me()?.id));$('.wmMain',v).innerHTML=`<div class="wmChat"><div class="wmChatHead"><button class="wmBackList">${I.back}</button><b>Nouveau message</b></div><div class="wmPeople">${list.map(u=>`<button data-new-peer="${esc(u.id)}">${avatar(u,'small')}<b>${esc(name(u))}</b></button>`).join('')||'<div class="wmEmpty">Aucun autre membre disponible.</div>'}</div></div>`;$('.wmLayout',v).classList.add('chatOpen');$('.wmBackList',v)?.addEventListener('click',()=>$('.wmLayout',v).classList.remove('chatOpen'));v.querySelectorAll('[data-new-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.newPeer))}
async function chat(id){peer=String(id);const v=ensure(),u=person(peer);draw($('.wmSearch input',v)?.value||'');$('.wmMain',v).innerHTML=`<div class="wmChat"><div class="wmChatHead"><button class="wmBackList">${I.back}</button>${avatar(u,'small')}<span class="wmPeer"><b>${esc(name(u))}</b><small>Conversation interne</small></span><button class="wmHeadAction" title="Appeler">${I.call}</button><button class="wmHeadAction wmInfoBtn" title="Infos">${I.info}</button></div><div class="wmMessages"><div class="wmDay">Aujourd’hui</div><div class="wmEmpty">Chargement…</div></div><div class="wmComposer"><button class="wmAttach" title="Pièce jointe">${I.clip}</button><textarea placeholder="Écrire un message…" rows="1"></textarea><button class="wmSend" title="Envoyer">${I.send}</button></div></div>`;$('.wmLayout',v).classList.add('chatOpen');$('.wmBackList',v).onclick=()=>{peer=null;$('.wmLayout',v).classList.remove('chatOpen');draw($('.wmSearch input',v)?.value||'')};$('.wmInfoBtn',v).onclick=()=>showInfo(u);$('.wmSend',v).onclick=send;$('.wmComposer textarea',v).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});await refreshChat()}
async function refreshChat(){if(!peer)return;const self=me(),box=$('#messaging .wmMessages');if(!box)return;try{const j=await post({action:'listInternalMessages',userId:self?.id||'',peerId:peer});box.innerHTML='<div class="wmDay">Aujourd’hui</div>'+((j.messages||[]).map(m=>`<div class="wmBubble ${String(m.senderId)===String(self?.id)?'mine':''}">${esc(m.text)}<small>${new Date(m.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}${String(m.senderId)===String(self?.id)?'<span class="wmChecks">✓✓</span>':''}</small></div>`).join('')||'<div class="wmEmpty">Écrivez le premier message.</div>');box.scrollTop=box.scrollHeight}catch(e){box.innerHTML=`<div class="wmEmpty">${esc(e.message)}</div>`}}
async function send(){const input=$('#messaging .wmComposer textarea'),text=input?.value.trim();if(!text||!peer)return;input.value='';try{await post({action:'sendInternalMessage',userId:me()?.id||'',recipientId:peer,text});await refreshChat();const j=await post({action:'listInternalConversations',userId:me()?.id||''});conversations=j.conversations||[];draw($('.wmSearch input',ensure())?.value||'')}catch(e){alert('Message non envoyé : '+e.message)}}
function showInfo(u){const v=ensure();$('.wmMain',v).innerHTML=`<div class="wmInfo"><div class="wmInfoTop"><button class="wmInfoBack">${I.back}</button><b>Infos du contact</b></div><div class="wmInfoCard wmProfile">${avatar(u,'big')}<h2>${esc(name(u))}</h2><p>${esc(u.function||u.role||'Membre de l’association')}</p><div class="wmInfoActions"><button>Message</button><button>Appel</button><button>Vidéo</button></div></div><div class="wmInfoCard"><div class="wmInfoRow"><span>E-mail</span><b>${esc(u.email||'Non renseigné')}</b></div><div class="wmInfoRow"><span>Téléphone</span><b>${esc(u.phone||'Non renseigné')}</b></div><div class="wmInfoRow"><span>Rôle</span><b>${esc(u.function||u.role||'Membre')}</b></div></div></div>`;$('.wmInfoBack',v).onclick=()=>chat(peer)}
function openHome(){peer=null;document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='home'));document.querySelector('.bottom')?.style.removeProperty('display');window.scrollTo(0,0)}
const tileIcon='<svg viewBox="0 0 24 24"><path d="M4 5h12a4 4 0 0 1 4 4v3a4 4 0 0 1-4 4h-5l-5 3 .8-3H4a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3Z"/><path d="M7 9h7M7 12h5"/></svg>';
function wire(){const grid=$('#home .grid,#home .dashGrid');if(grid&&!grid.querySelector('[data-module="messaging"]')){const b=document.createElement('button');b.className=grid.classList.contains('dashGrid')?'dashTile':'space';b.dataset.module='messaging';b.innerHTML=`<span class="ico">${tileIcon}</span><b>Messagerie</b><small>Messages internes de l’association</small>`;const compta=[...grid.children].find(x=>String(x.dataset?.permission||'').toLowerCase()==='comptabilite'||(x.textContent||'').toLowerCase().includes('comptabil'));grid.insertBefore(b,compta||null)}document.querySelectorAll('[data-module="messaging"]').forEach(b=>b.onclick=e=>{e.preventDefault();home()})}
wire();setInterval(()=>{wire();if(peer)refreshChat()},5000);window.addEventListener('horticulture-users-synced',wire);window.HorticultureMessaging={open:home};
})();