(()=>{
'use strict';
if(window.__horticultureMessagingV3)return;window.__horticultureMessagingV3=true;
const API='https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec',USERS='horticulture-admin-users-v2',SESSION='horticulture-admin-session-v1',PERSIST='horticulture-admin-persistent-session-v1';
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let peer=null,conversations=[];
const iconMessages=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5.5h9.5a4.5 4.5 0 0 1 4.5 4.5v1.5a4.5 4.5 0 0 1-4.5 4.5H10l-4.8 3.2.9-3.2H5A4 4 0 0 1 1 12V9.5a4 4 0 0 1 4-4Z"/><path d="M7 10h7M7 13h4.5"/></svg>`;
const iconSearch=`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>`;
const iconSend=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 5 16 7-16 7 3-7-3-7Z"/><path d="M7 12h13"/></svg>`;
function me(){try{return JSON.parse(localStorage.getItem(PERSIST)||sessionStorage.getItem(SESSION)||'null')}catch{return null}}
function users(){try{return JSON.parse(localStorage.getItem(USERS)||'[]').filter(x=>x.active!==false)}catch{return[]}}
function person(id){return users().find(x=>String(x.id)===String(id))||{id,firstName:'Membre'}}
function name(u){return [u.firstName,u.lastName].filter(Boolean).join(' ')||u.username||'Membre'}
function initials(u){return ((u.firstName?.[0]||'')+(u.lastName?.[0]||'')).toUpperCase()||'M'}
function avatar(u,small=false){return u?.photo?`<span class="msgAvatar ${small?'small':''}"><img src="${esc(u.photo)}" alt=""></span>`:`<span class="msgAvatar ${small?'small':''}">${esc(initials(u))}</span>`}
function when(v){if(!v)return'';const d=new Date(v),n=new Date();if(d.toDateString()===n.toDateString())return d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});const y=new Date(n);y.setDate(n.getDate()-1);if(d.toDateString()===y.toDateString())return'Hier';return d.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.','')}
async function post(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)}),j=await r.json();if(!j?.ok)throw Error(j?.error||'Erreur messagerie');return j}
function ensure(){let v=$('#messaging');if(v)return v;v=document.createElement('section');v.id='messaging';v.className='view';document.querySelector('#appShell main.app')?.appendChild(v);return v}
const css=`<style>
#messaging{--mg:#07583f;--mgd:#063d2f;--mline:#e1e8e3;--msoft:#f3f8f5;--mmut:#74817a;color:#173126}
#messaging svg{width:100%;height:100%;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
.msgShell{background:#fff;border:1px solid var(--mline);border-radius:24px;overflow:hidden;min-height:650px;box-shadow:0 14px 36px #0c3b2b0d}
.msgLayout{display:grid;grid-template-columns:330px minmax(0,1fr);min-height:650px}.msgSide{border-right:1px solid var(--mline);background:#fff}.msgSideHead{padding:18px 17px 14px;background:linear-gradient(180deg,#fff,#fbfdfc)}
.msgTopLine{display:flex;align-items:center;gap:10px}.msgBackHome,.msgBackList{border:0;background:transparent;color:var(--mg);font-weight:850;padding:8px 4px;border-radius:10px}.msgBackHome:hover,.msgBackList:hover{background:#edf6f0}.msgTitleWrap{min-width:0;flex:1}.msgTitle{font-size:24px;font-weight:900;color:var(--mgd);line-height:1.05}.msgSubtitle{font-size:11px;color:var(--mmut);margin-top:4px}.msgNew{width:40px;height:40px;border:0;border-radius:12px;background:var(--mg);color:#fff;font-size:25px;display:grid;place-items:center;box-shadow:0 7px 16px #07583f22}.msgNew:hover{background:#064c37}
.msgSearch{position:relative;margin-top:14px}.msgSearch input{width:100%;height:43px;border:1px solid #dbe5df;border-radius:13px;background:#f7faf8;padding:0 12px 0 41px;outline:none}.msgSearch input:focus{border-color:#9fc8b1;background:#fff;box-shadow:0 0 0 3px #e8f4ec}.msgSearch span{position:absolute;left:13px;top:11px;width:18px;height:18px;color:#849089}
.msgList{border-top:1px solid #eef2ef}.msgRow{width:100%;display:flex;align-items:center;gap:11px;border:0;border-bottom:1px solid #eef2ef;background:#fff;padding:13px;text-align:left;transition:.15s}.msgRow:hover{background:#f8fbf9}.msgRow.active{background:#edf7f1;box-shadow:inset 3px 0 0 var(--mg)}.msgAvatar{width:50px;height:50px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#dff0e5,#b9ddc6);color:var(--mg);font-weight:900;flex:0 0 auto;overflow:hidden;border:2px solid #fff;box-shadow:0 0 0 1px #dce8e0}.msgAvatar.small{width:42px;height:42px}.msgAvatar img{width:100%;height:100%;object-fit:cover}.msgMeta{min-width:0;flex:1}.msgMeta b{display:block;font-size:14px;color:#173126}.msgPreview{display:block;color:#75827b;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:4px}.msgRight{display:grid;gap:6px;justify-items:end}.msgTime{font-size:10px;color:#929b96}.msgUnread{min-width:20px;height:20px;padding:0 6px;border-radius:999px;background:var(--mg);color:#fff;font-size:10px;font-weight:900;display:grid;place-items:center}.msgEmpty{text-align:center;color:#7a8780;padding:42px 15px;line-height:1.55}
.msgMain{min-width:0;background:linear-gradient(180deg,#fbfdfc,#f4f8f5)}.msgWelcome{height:100%;display:grid;place-items:center;text-align:center;color:#74817a;padding:30px}.msgWelcomeCard{max-width:320px;padding:28px 24px;border:1px solid #e0e9e3;background:#fff;border-radius:22px;box-shadow:0 12px 30px #0c3b2b0d}.msgWelcomeIcon{width:66px;height:66px;border-radius:20px;background:#e8f4ec;color:var(--mg);display:grid;place-items:center;padding:15px;margin:0 auto 15px}.msgWelcome b{display:block;color:#173126;font-size:18px}.msgWelcome p{margin:7px 0 0;font-size:13px;line-height:1.45}
.msgChat{display:flex;flex-direction:column;height:650px}.msgChatHead{height:70px;display:flex;align-items:center;gap:11px;padding:0 17px;background:#fff;border-bottom:1px solid var(--mline)}.msgPeer{min-width:0}.msgPeer b{display:block;font-size:15px}.msgPeer small{display:block;color:#7b8781;margin-top:2px;font-size:11px}.msgMessages{flex:1;overflow:auto;padding:24px 20px;display:flex;flex-direction:column;gap:9px;background:linear-gradient(180deg,#f8fbf9,#f4f8f5)}.msgBubble{max-width:70%;padding:10px 13px;border-radius:18px 18px 18px 6px;background:#fff;border:1px solid #e1e8e3;align-self:flex-start;line-height:1.42;white-space:pre-wrap;box-shadow:0 3px 10px #17312608}.msgBubble.mine{background:#dff2e6;border-color:#c4e2cf;align-self:flex-end;border-radius:18px 18px 6px 18px}.msgBubble small{display:block;font-size:9px;color:#708078;margin-top:5px;text-align:right}.msgComposer{display:flex;gap:9px;align-items:flex-end;background:#fff;border-top:1px solid var(--mline);padding:11px 13px}.msgComposer textarea{flex:1;resize:none;min-height:44px;max-height:110px;border:1px solid #d7e1db;border-radius:18px;padding:11px 14px;outline:none;background:#fafcfb}.msgComposer textarea:focus{background:#fff;border-color:#9fc8b1;box-shadow:0 0 0 3px #e8f4ec}.msgSend{width:44px;height:44px;border:0;border-radius:50%;background:var(--mg);color:#fff;padding:11px;box-shadow:0 8px 18px #07583f22}.msgPeople{display:grid;gap:8px;padding:16px}.msgPeople button{display:flex;align-items:center;gap:11px;border:1px solid var(--mline);background:#fff;border-radius:14px;padding:10px;text-align:left}.msgPeople button:hover{background:#f7faf8}.msgMobileOnly{display:none}
@media(max-width:700px){#messaging{margin:-6px 0 0}.msgShell{border:0;border-radius:0;box-shadow:none;min-height:calc(100vh - 160px);background:transparent}.msgLayout{display:block;min-height:0}.msgSide{border:0}.msgMain{display:none}.msgSideHead{padding:4px 2px 12px}.msgTitle{font-size:27px}.msgSubtitle{display:none}.msgList{border:1px solid var(--mline);border-radius:18px;overflow:hidden;background:#fff}.msgRow{padding:13px 12px}.msgMobileOnly{display:inline-flex}.msgLayout.chatOpen .msgSide{display:none}.msgLayout.chatOpen .msgMain{display:block}.msgChat{height:calc(100vh - 145px);min-height:500px;background:#fff;border:1px solid var(--mline);border-radius:18px;overflow:hidden}.msgChatHead{height:62px;padding:0 10px}.msgMessages{padding:17px 11px}.msgBubble{max-width:84%}.msgComposer{padding-bottom:calc(10px + env(safe-area-inset-bottom))}.msgWelcome{display:none}}
</style>`;
function show(){document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='messaging'));$('#drawer')?.classList.remove('open');window.scrollTo(0,0)}
function shell(){const v=ensure();v.innerHTML=css+`<div class="msgShell"><div class="msgLayout"><aside class="msgSide"><div class="msgSideHead"><div class="msgTopLine"><button class="msgBackHome">← Retour</button><div class="msgTitleWrap"><div class="msgTitle">Messagerie</div><div class="msgSubtitle">Conversations internes de l’association</div></div><button class="msgNew" title="Nouveau message">＋</button></div><div class="msgSearch"><span>${iconSearch}</span><input placeholder="Rechercher une conversation…"></div></div><div class="msgList"><div class="msgEmpty">Chargement des conversations…</div></div></aside><main class="msgMain"><div class="msgWelcome"><div class="msgWelcomeCard"><div class="msgWelcomeIcon">${iconMessages}</div><b>Messagerie interne</b><p>Sélectionnez une conversation ou créez un nouveau message.</p></div></div></main></div></div>`;show();$('.msgBackHome',v).onclick=openHome;$('.msgNew',v).onclick=choose;$('.msgSearch input',v).oninput=e=>drawConversations(e.target.value)}
async function home(){peer=null;shell();const self=me();try{const j=await post({action:'listInternalConversations',userId:self?.id||''});conversations=j.conversations||[];drawConversations('')}catch(e){$('.msgList',ensure()).innerHTML=`<div class="msgEmpty">${esc(e.message)}</div>`}}
function drawConversations(q=''){const v=ensure(),needle=String(q||'').trim().toLowerCase();const list=conversations.filter(c=>{const u=person(c.otherUserId);return !needle||name(u).toLowerCase().includes(needle)||String(c.lastMessage||'').toLowerCase().includes(needle)});$('.msgList',v).innerHTML=list.length?list.map(c=>{const other=person(c.otherUserId);return `<button class="msgRow ${String(peer)===String(c.otherUserId)?'active':''}" data-peer="${esc(c.otherUserId)}">${avatar(other)}<span class="msgMeta"><b>${esc(name(other))}</b><span class="msgPreview">${esc(c.lastMessage||'Nouvelle conversation')}</span></span><span class="msgRight"><span class="msgTime">${esc(when(c.updatedAt))}</span>${Number(c.unread)>0?`<span class="msgUnread">${Number(c.unread)>99?'99+':Number(c.unread)}</span>`:''}</span></button>`}).join(''):`<div class="msgEmpty">${needle?'Aucune conversation trouvée.':'Aucune conversation.<br>Appuyez sur ＋ pour écrire à un membre.'}</div>`;v.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.peer))}
function choose(){const v=ensure(),self=me(),list=users().filter(x=>String(x.id)!==String(self?.id));$('.msgMain',v).innerHTML=`<div class="msgChat"><div class="msgChatHead"><button class="msgBackList msgMobileOnly">←</button><b>Nouveau message</b></div><div class="msgPeople">${list.map(u=>`<button data-new-peer="${esc(u.id)}">${avatar(u,true)}<b>${esc(name(u))}</b></button>`).join('')||'<div class="msgEmpty">Aucun autre membre disponible.</div>'}</div></div>`;$('.msgLayout',v).classList.add('chatOpen');$('.msgBackList',v)?.addEventListener('click',()=>$('.msgLayout',v).classList.remove('chatOpen'));v.querySelectorAll('[data-new-peer]').forEach(b=>b.onclick=()=>chat(b.dataset.newPeer))}
async function chat(id){peer=String(id);const v=ensure(),u=person(peer);drawConversations($('.msgSearch input',v)?.value||'');$('.msgMain',v).innerHTML=`<div class="msgChat"><div class="msgChatHead"><button class="msgBackList msgMobileOnly">←</button>${avatar(u,true)}<span class="msgPeer"><b>${esc(name(u))}</b><small>Conversation interne</small></span></div><div class="msgMessages"><div class="msgEmpty">Chargement…</div></div><div class="msgComposer"><textarea placeholder="Écrire un message…" rows="1"></textarea><button class="msgSend" title="Envoyer">${iconSend}</button></div></div>`;$('.msgLayout',v).classList.add('chatOpen');$('.msgBackList',v)?.addEventListener('click',()=>{peer=null;$('.msgLayout',v).classList.remove('chatOpen');drawConversations($('.msgSearch input',v)?.value||'')});$('.msgSend',v).onclick=send;$('.msgComposer textarea',v).addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});await refreshChat()}
async function refreshChat(){if(!peer)return;const self=me(),box=$('#messaging .msgMessages');if(!box)return;try{const j=await post({action:'listInternalMessages',userId:self?.id||'',peerId:peer});box.innerHTML=(j.messages||[]).map(m=>`<div class="msgBubble ${String(m.senderId)===String(self?.id)?'mine':''}">${esc(m.text)}<small>${new Date(m.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="msgEmpty">Écrivez le premier message.</div>';box.scrollTop=box.scrollHeight}catch(e){box.innerHTML=`<div class="msgEmpty">${esc(e.message)}</div>`}}
async function send(){const self=me(),input=$('#messaging .msgComposer textarea'),text=input?.value.trim();if(!text||!peer)return;input.value='';try{await post({action:'sendInternalMessage',userId:self?.id||'',recipientId:peer,text});await refreshChat();const j=await post({action:'listInternalConversations',userId:self?.id||''});conversations=j.conversations||[];drawConversations($('.msgSearch input',ensure())?.value||'')}catch(e){alert('Message non envoyé : '+e.message)}}
function openHome(){peer=null;document.querySelectorAll('#appShell main.app > .view').forEach(v=>v.classList.toggle('active',v.id==='home'));window.scrollTo(0,0)}
function wire(){const grid=$('#home .grid,#home .dashGrid');if(grid){let b=grid.querySelector('[data-module="messaging"]');if(!b){b=document.createElement('button');b.className=grid.classList.contains('dashGrid')?'dashTile':'space';b.dataset.module='messaging';b.innerHTML=`<span class="ico msgTileIcon">${iconMessages}</span><b>Messagerie</b><small>Messages internes de l’association</small>`}else b.querySelector('.ico')?.replaceChildren();if(!b.isConnected){const compta=grid.querySelector('[data-permission="comptabilite"]');grid.insertBefore(b,compta||null)}else{const adherents=grid.querySelector('[data-permission="adherents"]'),compta=grid.querySelector('[data-permission="comptabilite"]');if(compta&&b.nextElementSibling!==compta)grid.insertBefore(b,compta);if(adherents&&adherents.nextElementSibling!==b)grid.insertBefore(b,compta||adherents.nextSibling)}if(!b.innerHTML.includes('<svg'))b.innerHTML=`<span class="ico msgTileIcon">${iconMessages}</span><b>Messagerie</b><small>Messages internes de l’association</small>`;const ico=b.querySelector('.msgTileIcon');if(ico){ico.style.padding='10px';ico.style.color='#07583f'}b.onclick=e=>{e.preventDefault();home()}}document.querySelectorAll('[data-module="messaging"]').forEach(b=>{if(!b.onclick)b.onclick=e=>{e.preventDefault();home()}})}
wire();setInterval(()=>{wire();if(peer)refreshChat()},5000);window.addEventListener('horticulture-users-synced',wire);window.HorticultureMessaging={open:home};
})();