(()=>{
'use strict';
const API='https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec';
const qs=new URLSearchParams(location.search),userId=qs.get('userId')||'';
const list=document.getElementById('list'),readAll=document.getElementById('readAll');
const CACHE_KEY='horticulture-notification-inbox-cache-v2:'+userId;
let rows=[],localVersion=0,refreshSeq=0,busyAll=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=t=>String(t||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const label=t=>{t=key(t);if(t.includes('suggest'))return'Suggestion';if(t.includes('helloasso')||t.includes('membership')||t.includes('adherent'))return'Adhérents';if(t.includes('ag'))return'Assemblée générale';if(t.includes('sortie'))return'Sortie';if(t.includes('admin'))return'Administratif';return'Information'};
const icon=t=>{t=key(t);let p='<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>';if(t.includes('helloasso')||t.includes('membership')||t.includes('adherent'))p='<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>';else if(t.includes('suggest'))p='<path d="M9 18h6M10 22h4"/><path d="M8.5 14.5A6 6 0 1 1 15.5 14.5C14.5 15.3 14 16 14 18h-4c0-2-.5-2.7-1.5-3.5Z"/>';else if(t.includes('ag'))p='<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h5M8 16h3"/>';else if(t.includes('sortie'))p='<path d="M12 22c4-4 7-7.4 7-12a7 7 0 1 0-14 0c0 4.6 3 8 7 12Z"/><circle cx="12" cy="10" r="2"/>';return `<svg viewBox="0 0 24 24" aria-hidden="true">${p}</svg>`};
const ago=v=>{const d=new Date(v),m=Math.floor((Date.now()-d.getTime())/60000);if(!Number.isFinite(m))return'';if(m<1)return"À l’instant";if(m<60)return`Il y a ${m} min`;const h=Math.floor(m/60);if(h<24)return`Il y a ${h} h`;const j=Math.floor(h/24);return j===1?'Hier':`Il y a ${j} jours`};
async function post(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});const j=await r.json();if(!j?.ok)throw new Error(j?.error||'Erreur');return j}
function visibleRows(){const cutoff=Date.now()-30*86400000;return rows.filter(n=>!n.read&&(!n.createdAt||Date.parse(n.createdAt)>=cutoff))}
function saveCache(){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({at:Date.now(),rows}))}catch(_){}}
function loadCache(){try{const c=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'null');if(c&&Array.isArray(c.rows)&&Date.now()-Number(c.at||0)<10*60*1000){rows=c.rows;return true}}catch(_){}return false}
function render(){const v=visibleRows();window.parent.postMessage({source:'horticulture-notification-inbox',unread:v.length},location.origin);readAll.disabled=!v.length||busyAll;if(!v.length){list.className='empty';list.innerHTML='<div class="emptyIcon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg></div>Aucune nouvelle notification.';return}list.className='list';list.innerHTML=v.map(n=>`<button type="button" class="card" data-id="${esc(n.id)}"><div class="icon">${icon(n.type)}</div><div><b>${esc(n.title)}</b><p>${esc(n.message)}</p><div class="meta">${esc(label(n.type))} · ${esc(ago(n.createdAt))}</div></div><span class="chev" aria-hidden="true">›</span></button>`).join('')}
async function refresh(){if(!userId){list.className='error';list.textContent='Utilisateur non identifié.';return}const seq=++refreshSeq,startVersion=localVersion;try{const r=await fetch(`${API}?action=listNotifications&userId=${encodeURIComponent(userId)}&t=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!j?.ok)throw new Error(j?.error||'Lecture impossible');if(seq!==refreshSeq||startVersion!==localVersion)return;rows=Array.isArray(j.notifications)?j.notifications:[];saveCache();render()}catch(e){if(!rows.length){list.className='error';list.textContent='Impossible de charger les notifications.'}}}
if(loadCache())render();
refresh();
list.addEventListener('click',async e=>{const c=e.target.closest('.card');if(!c)return;const id=c.dataset.id,n=rows.find(x=>x.id===id);if(!n)return;localVersion++;n.read=true;saveCache();render();try{await post({action:'markNotificationRead',notificationId:id,userId});window.parent.postMessage({source:'horticulture-notification-inbox',action:'open-notification',notification:n},location.origin)}catch(e){n.read=false;localVersion++;saveCache();render()}});
readAll.addEventListener('click',async()=>{if(busyAll)return;const v=visibleRows();if(!v.length)return;busyAll=true;localVersion++;v.forEach(n=>n.read=true);saveCache();render();try{await post({action:'markAllNotificationsRead',userId});busyAll=false;render();window.parent.postMessage({source:'horticulture-notification-inbox',action:'read-all-done',unread:0},location.origin)}catch(e){v.forEach(n=>n.read=false);localVersion++;busyAll=false;saveCache();render()}});
})();