(()=>{
const USERS='horticulture-admin-users-v2',SK='horticulture-admin-session-v1',PK='horticulture-admin-persistent-session-v1';
const MAP=[{p:'communication',words:['Publier','Actualités','Nouvelle actualité','Nouvelle publication']},{p:'sorties',words:['Sorties','Sortie','Inscriptions']},{p:'adherents',words:['Adhérents','Adhérent']},{p:'comptabilite',words:['Comptabilité','Trésorerie']},{p:'suggestions',words:['Suggestions','Suggestion']},{p:'consultation_ag',words:['Consultation AG']},{p:'acces',words:['Gestion des accès']}];
function data(){try{return JSON.parse(localStorage.getItem(USERS)||'[]')}catch{return[]}}
function parse(raw){try{const s=JSON.parse(raw||'null');return s?.username?s:null}catch{return null}}
function session(){return parse(sessionStorage.getItem(SK))||parse(localStorage.getItem(PK))||null}
function user(){const s=session();if(!s)return null;const list=data();return list.find(u=>String(u.id)===String(s.id))||list.find(u=>String(u.username||'').toLowerCase()===String(s.username||'').toLowerCase())||((String(s.username||'').toLowerCase()==='superadmin'||s.role==='Super Admin')?{...s,role:'Super Admin',permissions:['communication','sorties','adherents','comptabilite','suggestions','consultation_ag','acces']}:s)}
function perms(u){return Array.isArray(u?.permissions)?u.permissions.map(x=>String(x).trim().toLowerCase()):String(u?.permissions||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean)}
function allowed(u,p){return u?.role==='Super Admin'||String(u?.username||'').toLowerCase()==='superadmin'||perms(u).includes(String(p||'').toLowerCase())}
function permissionFor(el){const explicit=el.dataset?.permission;if(explicit)return explicit;const t=(el.textContent||'').trim();for(const x of MAP)if(x.words.some(w=>t.includes(w)))return x.p;return null}
function apply(){const u=user();document.querySelectorAll('.dashTile,.quickBtn,.dlist button,[data-permission]').forEach(el=>{const p=permissionFor(el);if(!p)return;const ok=!!u&&allowed(u,p);el.style.setProperty('display',ok?'':'none','important');el.setAttribute('aria-hidden',ok?'false':'true')})}
document.addEventListener('click',e=>{const el=e.target.closest?.('[data-permission],.dashTile,.quickBtn,.dlist button');if(!el)return;const p=permissionFor(el),u=user();if(p&&(!u||!allowed(u,p))){e.preventDefault();e.stopImmediatePropagation()}},true);
window.addEventListener('storage',apply);window.addEventListener('horticulture-users-synced',apply);window.addEventListener('pageshow',apply);document.addEventListener('visibilitychange',()=>{if(!document.hidden)apply()});new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});setInterval(apply,750);setTimeout(apply,0);setTimeout(apply,300);
})();