(()=>{
const KEY='horticulture-app-settings-v1';
const defaults={theme:'system',textSize:'normal',reduceMotion:false,notifications:true,startPage:'last',confirmActions:true};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));apply(s)}
function apply(s=load()){
 const root=document.documentElement;
 root.dataset.appTheme=s.theme;root.dataset.textSize=s.textSize;
 root.classList.toggle('reduceMotion',!!s.reduceMotion);
 const dark=s.theme==='dark'||(s.theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);root.classList.toggle('appDark',dark);
 const scale=s.textSize==='large'?1.12:s.textSize==='xlarge'?1.24:1;root.style.setProperty('--user-font-scale',scale);
 document.body.style.fontSize=`calc(16px * ${scale})`;
}
function isSuper(){try{const raw=localStorage.getItem('horticulture-admin-persistent-session-v1')||sessionStorage.getItem('horticulture-admin-session-v1');const se=JSON.parse(raw||'null');if(!se)return false;const us=JSON.parse(localStorage.getItem('horticulture-admin-users-v2')||'[]');const u=us.find(x=>String(x.id)===String(se.id))||us.find(x=>x.username===se.username)||se;return u.username==='superadmin'||u.role==='Super Admin'}catch{return false}}
function row(title,desc,control){return `<div class="setRow"><div><b>${title}</b><small>${desc}</small></div>${control}</div>`}
function select(id,opts,val){return `<select id="${id}" class="setSelect">${opts.map(([v,l])=>`<option value="${v}" ${v===val?'selected':''}>${l}</option>`).join('')}</select>`}
function toggle(id,on){return `<label class="setSwitch"><input id="${id}" type="checkbox" ${on?'checked':''}><span></span></label>`}
function render(){const sec=document.getElementById('settings');if(!sec)return;const s=load();sec.innerHTML=`<button class="back" data-go="home">← Retour</button><div class="settingsPage"><div class="settingsHead"><div><h1>Paramètres</h1><p>Personnalisez l’application selon vos besoins.</p></div><div class="settingsStatus">✓ Paramètres enregistrés automatiquement</div></div>
 <section class="setCard"><h2>◐ Apparence</h2>${row('Thème','Choisissez l’apparence de l’application.',select('setTheme',[['system','Automatique'],['light','Clair'],['dark','Sombre']],s.theme))}${row('Taille du texte','Agrandit aussi légèrement les zones cliquables.',select('setTextSize',[['normal','Normal'],['large','Grand'],['xlarge','Très grand']],s.textSize))}${row('Réduire les animations','Limite les mouvements et transitions visuelles.',toggle('setMotion',s.reduceMotion))}</section>
 <section class="setCard"><h2>♢ Notifications</h2>${row('Notifications dans l’application','Alertes importantes dans la cloche de notification.',toggle('setNotif',s.notifications))}<div class="setHint">Les notifications par e-mail ne sont pas activées : les membres utilisent déjà la messagerie de l’association.</div></section>
 <section class="setCard"><h2>⚙ Préférences</h2>${row('Page au démarrage','Revenir à l’accueil ou à la dernière rubrique consultée.',select('setStart',[['last','Dernière page consultée'],['home','Accueil']],s.startPage))}${row('Confirmer les actions importantes','Demander une confirmation avant une suppression ou une action sensible.',toggle('setConfirm',s.confirmActions))}</section>
 <section class="setCard"><h2>⌾ Sécurité</h2>${row('Mot de passe','Modifiez votre mot de passe personnel.','<button class="setBtn" id="changePwd">Modifier</button>')}${row('Autres appareils','Déconnecter les autres sessions ouvertes avec ce compte.','<button class="setBtn" id="disconnectOthers">Déconnecter</button>')}<div class="setHint">La gestion détaillée des appareils sera ajoutée avec le système de sessions serveur.</div></section>
 <section class="setCard"><h2>☁ Synchronisation</h2>${row('Google Sheets','Base commune des comptes et autorisations.','<span class="syncBadge" id="syncState">● Synchronisé</span>')}${row('Synchroniser maintenant','Force une nouvelle lecture des données partagées.','<button class="setBtn" id="syncNow">Synchroniser</button>')}<small class="lastSync" id="lastSync">Dernière vérification : maintenant</small></section>
 <section class="setCard"><h2>ⓘ Application</h2>${row('Version','Version actuellement installée.','<b>V57</b>')}${row('Site public','Ouvrir le site de la Société d’Horticulture.','<button class="setBtn" id="publicSite">Ouvrir</button>')}</section>
 ${isSuper()?`<section class="setCard adminSet"><h2>♛ Administration</h2><div class="setHint">Cette partie est visible uniquement par le Super Admin.</div>${row('Gestion des accès','Créer les comptes et définir les rubriques autorisées.','<button class="setBtn" id="openAccess">Ouvrir</button>')}${row('Base partagée','État de la connexion à Google Sheets / Apps Script.','<span class="syncBadge">● Connectée</span>')}</section>`:''}</div>`;
 bind(sec,s);
}
function bind(sec,s){
 const upd=(k,v)=>{s[k]=v;save(s)};
 sec.querySelector('#setTheme')?.addEventListener('change',e=>upd('theme',e.target.value));sec.querySelector('#setTextSize')?.addEventListener('change',e=>upd('textSize',e.target.value));sec.querySelector('#setMotion')?.addEventListener('change',e=>upd('reduceMotion',e.target.checked));sec.querySelector('#setNotif')?.addEventListener('change',e=>upd('notifications',e.target.checked));sec.querySelector('#setStart')?.addEventListener('change',e=>upd('startPage',e.target.value));sec.querySelector('#setConfirm')?.addEventListener('change',e=>upd('confirmActions',e.target.checked));
 sec.querySelector('#syncNow')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Synchronisation…';try{await window.HorticultureSharedUsers?.pull?.();sec.querySelector('#syncState').textContent='● Synchronisé';sec.querySelector('#lastSync').textContent='Dernière vérification : à l’instant'}finally{b.disabled=false;b.textContent='Synchroniser'}});
 sec.querySelector('#publicSite')?.addEventListener('click',()=>window.open('https://sites.google.com/view/societehorticulturechateaulin/accueil','_blank','noopener'));
 sec.querySelector('#openAccess')?.addEventListener('click',()=>{const b=[...document.querySelectorAll('[data-permission="acces"],.dlist button')].find(x=>x.textContent.includes('Gestion des accès'));b?.click()});
 sec.querySelector('#changePwd')?.addEventListener('click',()=>alert('La modification du mot de passe sera reliée à Mon profil.'));
 sec.querySelector('#disconnectOthers')?.addEventListener('click',()=>alert('Cette fonction sera disponible lorsque les sessions seront enregistrées côté serveur.'));
 sec.querySelector('[data-go="home"]')?.addEventListener('click',()=>document.querySelector('.dlist button[data-go="home"]')?.click());
}
function installCss(){if(document.getElementById('settings-v1-style'))return;const st=document.createElement('style');st.id='settings-v1-style';st.textContent=`
.settingsPage{max-width:1120px;margin:0 auto;padding:4px 0 40px}.settingsHead{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;margin:12px 0 22px}.settingsHead h1{margin:0;color:#064b37;font-size:30px}.settingsHead p{margin:7px 0 0;color:#64736c}.settingsStatus{font-size:12px;color:#47705f;background:#edf7f0;border:1px solid #d9e9de;border-radius:999px;padding:8px 12px}.setCard{background:#fff;border:1px solid #e0e8e3;border-radius:18px;margin:14px 0;padding:8px 22px;box-shadow:0 5px 18px #17312608}.setCard h2{font-size:17px;color:#123d2f;margin:15px 0 8px}.setRow{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:17px 0;border-top:1px solid #edf0ee}.setRow:first-of-type{border-top:0}.setRow b{font-size:14px}.setRow small{display:block;color:#6a7871;margin-top:4px;font-size:12px}.setSelect,.setBtn{border:1px solid #d5dfd9;background:#fff;color:#173d30;border-radius:10px;padding:9px 12px;font:inherit}.setBtn{cursor:pointer;font-weight:700}.setSwitch input{display:none}.setSwitch span{display:block;width:45px;height:25px;background:#cbd4cf;border-radius:20px;position:relative;cursor:pointer}.setSwitch span:after{content:'';position:absolute;width:19px;height:19px;left:3px;top:3px;border-radius:50%;background:#fff;transition:.18s}.setSwitch input:checked+span{background:#08744f}.setSwitch input:checked+span:after{left:23px}.setHint{background:#f5f8f6;border-radius:11px;padding:11px 13px;color:#617068;font-size:12px;margin:8px 0 13px}.syncBadge{color:#08744f;font-weight:750;font-size:13px}.lastSync{display:block;color:#738078;padding:0 0 15px}.adminSet{border-color:#cfe3d6}.reduceMotion *{animation:none!important;transition:none!important}.appDark .appShell,.appDark .app{background:#17201c!important}.appDark .setCard{background:#222d28;border-color:#36443d;color:#eef4f0}.appDark .settingsHead h1,.appDark .setCard h2{color:#dff4e8}.appDark .settingsHead p,.appDark .setRow small,.appDark .lastSync{color:#aebdb5}.appDark .setRow{border-color:#36443d}.appDark .setSelect,.appDark .setBtn{background:#1b2521;color:#edf4f0;border-color:#45564e}.appDark .setHint{background:#1a2520;color:#b8c7bf}
html[data-text-size="large"] .settingsPage,html[data-text-size="large"] #home{font-size:1.08em}html[data-text-size="xlarge"] .settingsPage,html[data-text-size="xlarge"] #home{font-size:1.17em}html[data-text-size="large"] button,html[data-text-size="large"] select{min-height:44px}html[data-text-size="xlarge"] button,html[data-text-size="xlarge"] select{min-height:49px}
@media(max-width:760px){.settingsPage{padding:0 2px 85px}.settingsHead{display:block}.settingsStatus{display:inline-block;margin-top:12px}.setCard{padding:7px 15px;border-radius:15px}.setRow{align-items:flex-start}.setRow>div{max-width:65%}.setSelect{max-width:145px}.settingsHead h1{font-size:25px}}
`;document.head.appendChild(st)}
function hook(){installCss();apply();const buttons=[...document.querySelectorAll('[data-go="settings"],.dashTile,.quickBtn,.dlist button')].filter(b=>(b.textContent||'').includes('Paramètres'));buttons.forEach(b=>{if(b.dataset.settingsHook)return;b.dataset.settingsHook='1';b.addEventListener('click',()=>setTimeout(render,0))});if(document.getElementById('settings')&&getComputedStyle(document.getElementById('settings')).display!=='none')render()}
new MutationObserver(hook).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('pageshow',hook);setTimeout(hook,0);setTimeout(hook,600);
})();