(()=>{
const USERS_KEY='horticulture-admin-users-v2';
const API='https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec';
const POLL_MS=120000,TIMEOUT_MS=5000;let syncing=false,ready=false,queue=Promise.resolve(),pulling=false,localWritePending=0;const nativeSet=Storage.prototype.setItem,nativeRemove=Storage.prototype.removeItem;
window.__horticultureMessagingLogoExactV1=true;window.__horticultureUnifiedModuleIconsV2=true;window.__horticultureMessagingBrandExactV2=true;
['unifiedModuleIconsV1Style','unifiedModuleIconsV2Style','messagingBrandFinalV1Style','messagingBrandFinalV2Style'].forEach(id=>document.getElementById(id)?.remove());
async function fetchWithTimeout(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
async function request(body){const r=await fetchWithTimeout(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)}),text=await r.text();let j=null;try{j=JSON.parse(text)}catch{}if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`);return j}
async function listRemote(){const r=await fetchWithTimeout(API+'?action=listUsers&t='+Date.now(),{cache:'no-store'}),text=await r.text();let j=null;try{j=JSON.parse(text)}catch{}if(!r.ok||!j?.ok||!Array.isArray(j.users))throw new Error(j?.error||'Lecture impossible');return j.users}
function emit(users,source='remote'){window.dispatchEvent(new CustomEvent('horticulture-users-synced',{detail:{users,source}}))}function writeLocal(users){syncing=true;nativeSet.call(localStorage,USERS_KEY,JSON.stringify(users));syncing=false;emit(users,'remote')}
async function pull(force=false){if(pulling||(!force&&localWritePending>0)||(!force&&document.hidden))return null;pulling=true;try{const users=await listRemote(),before=localStorage.getItem(USERS_KEY)||'[]',after=JSON.stringify(users);if(before!==after)writeLocal(users);ready=true;return users}catch(e){console.warn('Shared users pull failed',e);return null}finally{pulling=false}}
async function syncChange(oldUsers,newUsers){const oldMap=new Map((oldUsers||[]).map(u=>[String(u.id),u])),newMap=new Map((newUsers||[]).map(u=>[String(u.id),u]));for(const[id,u]of newMap){const old=oldMap.get(id);if(!old)await request({action:'createUser',user:u});else if(JSON.stringify(old)!==JSON.stringify(u))await request({action:'updateUser',user:u})}for(const[id]of oldMap)if(!newMap.has(id))await request({action:'deleteUser',id})}
Storage.prototype.setItem=function(k,v){if(this!==localStorage||k!==USERS_KEY||syncing)return nativeSet.call(this,k,v);let oldUsers=[],newUsers=[];try{oldUsers=JSON.parse(localStorage.getItem(USERS_KEY)||'[]');newUsers=JSON.parse(v||'[]')}catch{return nativeSet.call(this,k,v)}nativeSet.call(this,k,v);emit(newUsers,'local');if(!ready)return;localWritePending++;queue=queue.then(async()=>{try{await syncChange(oldUsers,newUsers)}finally{localWritePending=Math.max(0,localWritePending-1)}await pull(true)}).catch(async e=>{localWritePending=Math.max(0,localWritePending-1);console.warn('Shared users write failed',e);await pull(true)})};
Storage.prototype.removeItem=function(k){if(this===localStorage&&k===USERS_KEY&&!syncing){nativeRemove.call(this,k);emit([],'local');return}return nativeRemove.call(this,k)};
setTimeout(()=>pull(true),250);setInterval(()=>pull(false),POLL_MS);window.addEventListener('focus',()=>pull(false));window.addEventListener('pageshow',()=>pull(false));document.addEventListener('visibilitychange',()=>{if(!document.hidden)pull(false)});window.HorticultureSharedUsers={api:API,pull:()=>pull(false)};
if(!document.getElementById('documentsCloudGlobalV5')){['documentsCloudGlobalV4'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='documentsCloudGlobalV5';s.src='./documents-cloud-archive-v1.js?v=5';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('cloudUiBridgeV5')){['iphoneUiBridgeV1','iphoneUiBridgeV2','iphoneUiBridgeV3','iphoneUiBridgeV4'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='cloudUiBridgeV5';s.src='./iphone-ui-bridge-v1.js?v=5';s.async=false;document.head.appendChild(s)}
['messagingNavigationFixV1'].forEach(id=>document.getElementById(id)?.remove());
if(!document.getElementById('messagingNavigationFixV2')){const s=document.createElement('script');s.id='messagingNavigationFixV2';s.src='./messaging-navigation-fix-v1.js?v=2';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingV6')){['messagingV1','messagingV2','messagingV3','messagingV4','messagingV5'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='messagingV6';s.src='./messaging-v6.js?v=1';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingPolishV12')){['messagingPolishV1','messagingPolishV2','messagingPolishV3','messagingPolishV4','messagingPolishV5','messagingPolishV6','messagingPolishV7','messagingPolishV8','messagingPolishV9','messagingPolishV10','messagingPolishV11'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='messagingPolishV12';s.src='./messaging-polish-v1.js?v=12';s.async=false;document.head.appendChild(s)}
['messagingLogoV1','messagingLogoV2','messagingLogoV3','messagingBrandFinalV1','messagingBrandFinalV2','messagingBrandFinalV3','moduleIconsUnifiedV1','moduleIconsUnifiedV2','moduleIconsUnifiedV3','moduleIconsUnifiedV4','moduleIconsUnifiedV5','moduleIconsUnifiedV6','moduleIconsUnifiedV7'].forEach(id=>document.getElementById(id)?.remove());
if(!document.getElementById('moduleIconsUnifiedV8')){const s=document.createElement('script');s.id='moduleIconsUnifiedV8';s.src='./module-icons-unified-v1.js?v=8';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('drawerIconSanitizerV1')){const s=document.createElement('script');s.id='drawerIconSanitizerV1';s.src='./drawer-icon-sanitizer-v1.js?v=1';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('adherentsAdminV2')){const s=document.createElement('script');s.id='adherentsAdminV2';s.src='./adherents-admin-v2.js?v=7';s.async=true;document.head.appendChild(s)}
if(!document.getElementById('adherentsImportReviewV1')){const s=document.createElement('script');s.id='adherentsImportReviewV1';s.src='./adherents-import-review-v1.js?v=3';s.async=true;document.head.appendChild(s)}
if(!document.getElementById('drawerControllerV3')){const s=document.createElement('script');s.id='drawerControllerV3';s.src='./drawer-controller-v1.js?v=3';s.async=true;document.head.appendChild(s)}
})();