(()=>{
const USERS_KEY='horticulture-admin-users-v2';
const API='https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec';
const POLL_MS=120000,TIMEOUT_MS=5000;let syncing=false,ready=false,queue=Promise.resolve(),pulling=false,localWritePending=0;const nativeSet=Storage.prototype.setItem,nativeRemove=Storage.prototype.removeItem;
window.__horticultureMessagingLogoExactV1=true;window.__horticultureUnifiedModuleIconsV2=true;window.__horticultureMessagingBrandExactV2=true;
['unifiedModuleIconsV1Style','unifiedModuleIconsV2Style','messagingBrandFinalV1Style','messagingBrandFinalV2Style'].forEach(id=>document.getElementById(id)?.remove());
async function fetchWithTimeout(url,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
async function request(body){const r=await fetchWithTimeout(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)}),text=await r.text();let j=null;try{j=JSON.parse(text)}catch{}if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`);return j}
async function listRemote(){const r=await fetchWithTimeout(API+'?action=listUsers&t='+Date.now(),{cache:'no-store'}),text=await r.text();let j=null;try{j=JSON.parse(text)}catch{}if(!r.ok||!j?.ok||!Array.isArray(j.users))throw new Error(j?.error||'Lecture impossible');return j.users}
function emit(users,source='remote'){window.dispatchEvent(new CustomEvent('horticulture-users-synced',{detail:{users,source}}))}function writeLocal(users){syncing=true;nativeSet.call(localStorage,USERS_KEY,JSON.stringify(users));syncing=false;emit(users,'remote')}
async function pull(force=false){if(pulling||(!force&&localWritePending>0)||(!force&&document.hidden))return null;pulling=true;try{const users=await listRemote(),before=localStorage.getItem(USERS_KEY)||'[]',after=JSON.stringify(users);if(before!==after)writeLocal(users);ready=true;return users}catch(e){console.warn('Shared users pull failed',e);return null}finally{pulling=false}}
async function syncChange(oldUsers,newUsers){const oldMap=new Map((oldUsers||[]).map(u=>[String(u.id),u])),newMap=new Map((newUsers||[]).map(u=>[String(u.id),u]));for(const[id,u]of newMap){const old=oldMap.get(id);if(!old)await request({action:'createUser',user:u});else if(JSON.stringify(old)!==JSON.stringify(u))await request({action:'updateUser',user:u})}for(const[id]of oldMap)if(!newMap.has(id))await request({action:'deleteUser',id})}
Storage.prototype.setItem=function(k,v){if(this!==localStorage||k!==USERS_KEY||syncing)return nativeSet.call(this,k,v);let oldUsers=[],newUsers=[];try{oldUsers=JSON.parse(localStorage.getItem(USERS_KEY)||'[]');newUsers=JSON.parse(v||'[]')}catch{return nativeSet.call(this,k,v)}nativeSet.call(this,k,v);emit(newUsers,'local');if(!ready)return;localWritePending++;queue=queue.then(async()=>{try{await syncChange(oldUsers,newUsers)}finally{localWritePending=Math.max(0,localWritePending-1)}await pull(true)}).catch(async e=>{localWritePending=Math.max(0,localWritePending-1);console.warn('Shared users write failed',e);await pull(true)})};
Storage.prototype.removeItem=function(k){if(this===localStorage&&k===USERS_KEY&&!syncing){nativeRemove.call(this,k);emit([],'local');return}return nativeRemove.call(this,k)};
setTimeout(()=>pull(true),250);setInterval(()=>pull(false),POLL_MS);window.addEventListener('focus',()=>pull(false));window.addEventListener('pageshow',()=>pull(false));document.addEventListener('visibilitychange',()=>{if(!document.hidden)pull(false)});window.HorticultureSharedUsers={api:API,pull:()=>pull(false)};
if(!document.getElementById('documentsCloudGlobalV5')){['documentsCloudGlobalV4'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='documentsCloudGlobalV5';s.src='./documents-cloud-archive-v1.js?v=5';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('cloudUiBridgeV5')){['iphoneUiBridgeV1','iphoneUiBridgeV2','iphoneUiBridgeV3','iphoneUiBridgeV4'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='cloudUiBridgeV5';s.src='./iphone-ui-bridge-v1.js?v=5';s.async=false;document.head.appendChild(s)}
['messagingNavigationFixV1','messagingNavigationFixV2','messagingNavigationFixV3','messagingNavigationFixV4','messagingNavigationFixV5','messagingNavigationFixV6','messagingNavigationFixV7','messagingNavigationFixV8','messagingNavigationFixV9'].forEach(id=>document.getElementById(id)?.remove());
if(!document.getElementById('messagingNavigationFixV10')){const s=document.createElement('script');s.id='messagingNavigationFixV10';s.src='./messaging-navigation-fix-v1.js?v=10';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('supabaseJsV2')){const s=document.createElement('script');s.id='supabaseJsV2';s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingAuthBridgeV1')){const s=document.createElement('script');s.id='messagingAuthBridgeV1';s.src='./messaging-auth-bridge-v1.js?v=1';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingSupabaseV3')){['messagingSupabaseV1','messagingSupabaseV2'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='messagingSupabaseV3';s.src='./messaging-supabase-v1.js?v=3';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingSupabaseTransportV3')){['messagingSupabaseTransportV1','messagingSupabaseTransportV2'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='messagingSupabaseTransportV3';s.src='./messaging-supabase-transport-v1.js?v=3';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingGroupsV1')){const s=document.createElement('script');s.id='messagingGroupsV1';s.src='./messaging-groups-v1.js?v=1';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingInstantCacheV3')){['messagingInstantCacheV1','messagingInstantCacheV2'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='messagingInstantCacheV3';s.src='./messaging-instant-cache-v1.js?v=3';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingV6')){['messagingV1','messagingV2','messagingV3','messagingV4','messagingV5'].forEach(id=>document.getElementById(id)?.remove());const s=document.createElement('script');s.id='messagingV6';s.src='./messaging-v6.js?v=1';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingDeviceSyncV1')){const s=document.createElement('script');s.id='messagingDeviceSyncV1';s.src='./messaging-device-sync-fix-v1.js?v=1';s.async=false;document.head.appendChild(s)}
['messagingMessageActionsV1','messagingMessageActionsV2','messagingMessageActionsV3'].forEach(id=>document.getElementById(id)?.remove());
if(!document.getElementById('messagingMessageActionsV4')){const s=document.createElement('script');s.id='messagingMessageActionsV4';s.src='./messaging-message-actions-v1.js?v=4';s.async=false;document.head.appendChild(s)}
['messagingReplyWallpaperV1','messagingReplyWallpaperV2'].forEach(id=>document.getElementById(id)?.remove());
if(!document.getElementById('messagingReplyWallpaperV3')){const s=document.createElement('script');s.id='messagingReplyWallpaperV3';s.src='./messaging-reply-wallpaper-v1.js?v=3';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('messagingHardDeleteV1')){const s=document.createElement('script');s.id='messagingHardDeleteV1';s.src='./messaging-hard-delete-v1.js?v=1';s.async=false;document.head.appendChild(s)}
['messagingNativeCallsV1','messagingNativeCallsV2'].forEach(id=>document.getElementById(id)?.remove());
if(!document.getElementById('messagingNativeCallsV3')){const s=document.createElement('script');s.id='messagingNativeCallsV3';s.src='./messaging-native-calls-v1.js?v=3';s.async=false;document.head.appendChild(s)}
['messagingPolishV1','messagingPolishV2','messagingPolishV3','messagingPolishV4','messagingPolishV5','messagingPolishV6','messagingPolishV7','messagingPolishV8','messagingPolishV9','messagingPolishV10','messagingPolishV11','messagingPolishV12','messagingPolishV13'].forEach(id=>document.getElementById(id)?.remove());
if(!document.getElementById('messagingPolishV14')){const s=document.createElement('script');s.id='messagingPolishV14';s.src='./messaging-polish-v1.js?v=14';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('moduleIconsUnifiedV8')){const s=document.createElement('script');s.id='moduleIconsUnifiedV8';s.src='./module-icons-unified-v1.js?v=8';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('drawerIconsSanitizeV3')){const s=document.createElement('script');s.id='drawerIconsSanitizeV3';s.src='./drawer-icons-sanitize-v1.js?v=3';s.async=false;document.head.appendChild(s)}
if(!document.getElementById('adherentsAdminV2')){const s=document.createElement('script');s.id='adherentsAdminV2';s.src='./adherents-admin-v2.js?v=7';s.async=true;document.head.appendChild(s)}
if(!document.getElementById('adherentsImportReviewV1')){const s=document.createElement('script');s.id='adherentsImportReviewV1';s.src='./adherents-import-review-v1.js?v=3';s.async=true;document.head.appendChild(s)}
if(!document.getElementById('drawerControllerV7')){const s=document.createElement('script');s.id='drawerControllerV7';s.src='./drawer-controller-v1.js?v=7';s.async=true;document.head.appendChild(s)}
})();