(()=>{
'use strict';
if(window.__horticultureSortiesSafeV1)return;
window.__horticultureSortiesSafeV1=true;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const icon=(name)=>({back:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 18l-6-6 6-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',plus:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',scan:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3M8 8h3v3H8zM13 8h3v3h-3zM8 13h3v3H8zM13 13h3v3h-3z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg>',sync:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 7h-5V2M4 17h5v5M19 9a7 7 0 0 0-12-3L4 9M5 15a7 7 0 0 0 12 3l3-3" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>'}[name]||'');
function ensureStyle(){if($('#sortiesSafeStyle'))return;const s=document.createElement('style');s.id='sortiesSafeStyle';s.textContent=`#sortiesAdmin{max-width:980px;margin:0 auto}.sfs-top{display:flex;align-items:center;gap:12px;margin-bottom:18px}.sfs-back{border:0;background:transparent;color:#07583f;display:inline-flex;align-items:center;gap:6px;font-weight:800;padding:7px 2px}.sfs-back svg,.sfs-btn svg{width:19px;height:19px}.sfs-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:18px}.sfs-head h1{margin:0;color:#173126;font-size:30px}.sfs-sub{color:#6d7d75;font-size:13px;margin-top:4px}.sfs-actions{display:flex;gap:9px;flex-wrap:wrap}.sfs-btn{border:1px solid #dbe5df;background:#fff;color:#173126;border-radius:12px;padding:10px 14px;font-weight:800;display:inline-flex;align-items:center;gap:8px}.sfs-btn.primary{background:#07583f;color:#fff;border-color:#07583f}.sfs-tabs{display:flex;gap:24px;border-bottom:1px solid #e1e8e3;margin-bottom:14px}.sfs-tab{border:0;background:transparent;padding:11px 2px;font-weight:800;color:#758078;border-bottom:2px solid transparent}.sfs-tab.active{color:#07583f;border-color:#07583f}.sfs-card{background:#fff;border:1px solid #e1e8e3;border-radius:18px;padding:28px;text-align:center}.sfs-emptyIcon{width:54px;height:54px;border-radius:16px;background:#edf6f0;display:grid;place-items:center;margin:0 auto 12px;color:#07583f}.sfs-emptyIcon svg{width:28px;height:28px}.sfs-card h2{font-size:18px;margin:0 0 7px}.sfs-card p{margin:0;color:#6d7d75;font-size:13px}.sfs-note{margin-top:12px;background:#edf7f1;border:1px solid #d4e8db;border-radius:14px;padding:12px 14px;color:#3b6751;font-size:12px}.sfs-pickerBack{position:fixed;inset:0;background:#071a1377;z-index:1000;display:grid;place-items:center;padding:16px}.sfs-picker{width:min(100%,430px);background:#fff;border-radius:22px;padding:20px}.sfs-picker h2{margin:0 0 6px}.sfs-picker p{margin:0 0 14px;color:#6d7d75;font-size:13px}.sfs-picker .sfs-btn{width:100%;justify-content:center}.sfs-close{margin-top:8px}.sfs-mobileScan svg{width:22px;height:22px;display:block;margin:0 auto 2px}@media(max-width:700px){.sfs-head{display:block}.sfs-actions{margin-top:14px}.sfs-actions .sfs-btn{flex:1;justify-content:center}.sfs-head h1{font-size:27px}.sfs-card{padding:24px 18px}}`;document.head.appendChild(s)}
function ensureView(){ensureStyle();let v=$('#sortiesAdmin');if(v)return v;v=document.createElement('section');v.id='sortiesAdmin';v.className='view';const main=$('#appShell main.app');if(main)main.appendChild(v);return v}
function home(){if(window.HorticultureDrawer?.home)window.HorticultureDrawer.home();else $$('#appShell main.app>.view').forEach(v=>v.classList.toggle('active',v.id==='home'))}
function render(){const v=ensureView();if(!v)return;v.innerHTML=`<div class="sfs-top"><button class="sfs-back" data-sfs-back>${icon('back')} Retour</button></div><div class="sfs-head"><div><h1>Sorties</h1><div class="sfs-sub">Gérer les sorties et les inscriptions</div></div><div class="sfs-actions"><button class="sfs-btn" data-sfs-sync>${icon('sync')} Synchroniser HelloAsso</button><button class="sfs-btn primary" data-sfs-new>${icon('plus')} Ajouter une sortie</button></div></div><div class="sfs-tabs"><button class="sfs-tab active">À venir</button><button class="sfs-tab">Passées</button></div><div class="sfs-card"><div class="sfs-emptyIcon">${icon('scan')}</div><h2>Module Sorties prêt</h2><p>La page est de nouveau accessible sans perturber le reste de l’application.</p></div><div class="sfs-note">La synchronisation HelloAsso et le contrôle des billets seront raccordés progressivement sur cette base stable.</div>`;const b=$('[data-sfs-back]',v);if(b)b.onclick=home;const sync=$('[data-sfs-sync]',v);if(sync)sync.onclick=()=>alert('La synchronisation HelloAsso sera activée à l’étape suivante.');const add=$('[data-sfs-new]',v);if(add)add.onclick=()=>alert('L’ajout manuel de sortie sera activé à l’étape suivante.')}
function open(){const v=ensureView();render();if(window.HorticultureDrawer?.activate)window.HorticultureDrawer.activate('sortiesAdmin');else $$('#appShell main.app>.view').forEach(x=>x.classList.toggle('active',x===v));window.scrollTo(0,0)}
function chooseScanner(){const b=document.createElement('div');b.className='sfs-pickerBack';b.innerHTML=`<div class="sfs-picker"><h2>Scanner les billets</h2><p>Aucune sortie disponible pour le moment.</p><button class="sfs-btn sfs-close">Fermer</button></div>`;document.body.appendChild(b);$('.sfs-close',b).onclick=()=>b.remove();b.onclick=e=>{if(e.target===b)b.remove()}}
document.addEventListener('click',e=>{const t=e.target.closest?.('[data-permission="sorties"]');if(t&&t.closest('#appShell')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open();return}const c=e.target.closest?.('[data-go="check"]');if(c&&c.closest('#appShell')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();chooseScanner()}},true);
function fixScanNav(){$$('[data-go="check"]').forEach(b=>{if(b.dataset.sfsDone)return;b.dataset.sfsDone='1';b.classList.add('sfs-mobileScan');b.innerHTML=icon('scan')+'<span>Scanner</span>'})}
fixScanNav();
window.HorticultureSorties={open,scan:chooseScanner};
})();