-- Horticulture messaging V6 — native WebRTC calls + WhatsApp-like message actions
-- Run once in Supabase SQL editor.

alter table public.horticulture_messages
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

-- Own messages can be soft-deleted. Reading remains controlled by existing RLS.
drop policy if exists horticulture_messages_update_own on public.horticulture_messages;
create policy horticulture_messages_update_own
on public.horticulture_messages
for update
to authenticated
using (
  sender_id = public.horticulture_auth_app_user_id()
  and public.horticulture_is_conversation_member(conversation_id)
)
with check (
  sender_id = public.horticulture_auth_app_user_id()
  and public.horticulture_is_conversation_member(conversation_id)
);

grant update (deleted_at, deleted_by, body) on public.horticulture_messages to authenticated;

create table if not exists public.horticulture_calls (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.horticulture_conversations(id) on delete cascade,
  caller_id text not null,
  mode text not null check (mode in ('audio','video')),
  participants text[] not null default '{}',
  status text not null default 'ringing' check (status in ('ringing','active','ended','declined','missed')),
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz
);

create index if not exists horticulture_calls_participants_gin
  on public.horticulture_calls using gin(participants);
create index if not exists horticulture_calls_created_at_idx
  on public.horticulture_calls(created_at desc);

create table if not exists public.horticulture_call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.horticulture_calls(id) on delete cascade,
  sender_id text not null,
  target_id text not null,
  signal_type text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists horticulture_call_signals_target_idx
  on public.horticulture_call_signals(target_id, created_at desc);
create index if not exists horticulture_call_signals_call_idx
  on public.horticulture_call_signals(call_id, created_at desc);

alter table public.horticulture_calls enable row level security;
alter table public.horticulture_call_signals enable row level security;

create or replace function public.horticulture_is_call_participant(p_call_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.horticulture_calls c
    where c.id = p_call_id
      and public.horticulture_auth_app_user_id() = any(c.participants)
  )
$$;

revoke all on function public.horticulture_is_call_participant(uuid) from public, anon;
grant execute on function public.horticulture_is_call_participant(uuid) to authenticated;

drop policy if exists horticulture_calls_select_participant on public.horticulture_calls;
create policy horticulture_calls_select_participant
on public.horticulture_calls for select to authenticated
using (public.horticulture_auth_app_user_id() = any(participants));

drop policy if exists horticulture_calls_insert_caller on public.horticulture_calls;
create policy horticulture_calls_insert_caller
on public.horticulture_calls for insert to authenticated
with check (
  caller_id = public.horticulture_auth_app_user_id()
  and caller_id = any(participants)
  and public.horticulture_is_conversation_member(conversation_id)
);

drop policy if exists horticulture_calls_update_participant on public.horticulture_calls;
create policy horticulture_calls_update_participant
on public.horticulture_calls for update to authenticated
using (public.horticulture_auth_app_user_id() = any(participants))
with check (public.horticulture_auth_app_user_id() = any(participants));

drop policy if exists horticulture_call_signals_select_participant on public.horticulture_call_signals;
create policy horticulture_call_signals_select_participant
on public.horticulture_call_signals for select to authenticated
using (
  public.horticulture_is_call_participant(call_id)
  and (sender_id = public.horticulture_auth_app_user_id() or target_id = public.horticulture_auth_app_user_id())
);

drop policy if exists horticulture_call_signals_insert_sender on public.horticulture_call_signals;
create policy horticulture_call_signals_insert_sender
on public.horticulture_call_signals for insert to authenticated
with check (
  sender_id = public.horticulture_auth_app_user_id()
  and public.horticulture_is_call_participant(call_id)
);

grant select, insert, update on public.horticulture_calls to authenticated;
grant select, insert on public.horticulture_call_signals to authenticated;
grant usage, select on sequence public.horticulture_call_signals_id_seq to authenticated;

-- Realtime publication (safe if already present).
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='horticulture_calls'
  ) then
    alter publication supabase_realtime add table public.horticulture_calls;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='horticulture_call_signals'
  ) then
    alter publication supabase_realtime add table public.horticulture_call_signals;
  end if;
end $$;
