// Documents.gs — stockage partagé des documents générés dans Google Drive.
// Déployé dans le même projet Apps Script que Code.gs.
const DOC_ROOT_PROP='DOCUMENTS_ROOT_FOLDER_ID';
const DOC_INDEX_SHEET='Documents Cloud';
const DOC_HEADERS=['key','driveId','name','folder','mimeType','size','updatedAt','createdAt','createdBy','source'];
function docsAuth_(userId,generation){
  userId=String(userId||'').trim();generation=String(generation||'').trim();
  if(!userId||!generation)return{ok:false,error:'Session manquante.'};
  const u=listUsers_().find(x=>String(x.id)===userId&&x.active);if(!u)return{ok:false,error:'Utilisateur introuvable.'};
  const server=sessionGeneration_(userId);if(!server||server!==generation)return{ok:false,error:'Session expirée.',sessionExpired:true};
  return{ok:true,user:u};
}
function docsSheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(DOC_INDEX_SHEET);if(!sh)sh=ss.insertSheet(DOC_INDEX_SHEET);if(sh.getLastRow()===0)sh.appendRow(DOC_HEADERS);return sh}
function docsRoot_(){const p=PropertiesService.getScriptProperties();let id=p.getProperty(DOC_ROOT_PROP),f=null;if(id){try{f=DriveApp.getFolderById(id)}catch(_){}}if(!f){f=DriveApp.createFolder('Horticulture - Documents');p.setProperty(DOC_ROOT_PROP,f.getId())}return f}
function docsFolder_(path){let cur=docsRoot_();String(path||'Documents générés').split('/').filter(Boolean).forEach(name=>{const it=cur.getFoldersByName(name);cur=it.hasNext()?it.next():cur.createFolder(name)});return cur}
function docsRows_(){const sh=docsSheet_();if(sh.getLastRow()<2)return[];return sh.getRange(2,1,sh.getLastRow()-1,DOC_HEADERS.length).getValues()}
function docsList_(userId,generation){const a=docsAuth_(userId,generation);if(!a.ok)return a;return{ok:true,documents:docsRows_().filter(r=>r[0]).map(r=>({key:String(r[0]),driveId:String(r[1]),name:String(r[2]),folder:String(r[3]),mimeType:String(r[4]),size:Number(r[5]||0),updatedAt:String(r[6]),createdAt:String(r[7]),createdBy:String(r[8]),source:String(r[9])}))}}
function docsUpsert_(b){const a=docsAuth_(b.userId,b.generation);if(!a.ok)return a;const key=String(b.key||'').trim();if(!key)return{ok:false,error:'Clé document manquante.'};const bytes=Utilities.base64Decode(String(b.base64||''));const mime=String(b.mimeType||'application/octet-stream'),name=String(b.name||'Document'),folder=String(b.folder||'Documents générés');const sh=docsSheet_(),rows=docsRows_();let row=-1,existingId='';for(let i=0;i<rows.length;i++)if(String(rows[i][0])===key){row=i+2;existingId=String(rows[i][1]||'');break}let file=null;if(existingId){try{file=DriveApp.getFileById(existingId)}catch(_){}}const blob=Utilities.newBlob(bytes,mime,name);if(file){file.setContent(blob.getBytes());file.setName(name)}else file=docsFolder_(folder).createFile(blob);const now=new Date().toISOString(),created=row?String(sh.getRange(row,8).getValue()||now):now,data=[key,file.getId(),name,folder,mime,bytes.length,now,created,String(a.user.id||''),String(b.source||'Application')];if(row)sh.getRange(row,1,1,DOC_HEADERS.length).setValues([data]);else sh.appendRow(data);return{ok:true,document:{key:key,driveId:file.getId(),name:name,folder:folder,mimeType:mime,size:bytes.length,updatedAt:now,createdAt:created,createdBy:String(a.user.id||''),source:String(b.source||'Application')},deduplicated:!!row}}
function docsDownload_(b){const a=docsAuth_(b.userId,b.generation);if(!a.ok)return a;const key=String(b.key||''),r=docsRows_().find(x=>String(x[0])===key);if(!r)return{ok:false,error:'Document introuvable.'};try{const f=DriveApp.getFileById(String(r[1]));const blob=f.getBlob();return{ok:true,name:String(r[2]),mimeType:String(r[4]||blob.getContentType()),base64:Utilities.base64Encode(blob.getBytes())}}catch(e){return{ok:false,error:String(e)}}
function docsRoutePost_(b){if(b.action==='listDocumentsCloud')return docsList_(b.userId||'',b.generation||'');if(b.action==='upsertDocumentCloud')return docsUpsert_(b);if(b.action==='downloadDocumentCloud')return docsDownload_(b);return null}
function initialiserDocumentsCloud(){docsRoot_();docsSheet_();['Documents générés/Consultations AG','Documents générés/Sorties','Documents générés/Adhérents','Fichiers'].forEach(docsFolder_);return'Documents Cloud prêt.'}
