const MSG_SHEET='Messagerie';
const MSG_HEADERS=['id','senderId','recipientId','text','createdAt','readAt'];
function msgSheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(MSG_SHEET);if(!sh)sh=ss.insertSheet(MSG_SHEET);if(sh.getLastRow()===0)sh.appendRow(MSG_HEADERS);return sh}
function msgUser_(id){return sessionUser_(String(id||''))}
function msgRows_(){const v=msgSheet_().getDataRange().getValues();return v.length<2?[]:v.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),senderId:String(r[1]),recipientId:String(r[2]),text:String(r[3]||''),createdAt:String(r[4]||''),readAt:String(r[5]||'')}))}
function sendInternalMessage_(b){const from=msgUser_(b.userId),to=msgUser_(b.recipientId),text=String(b.text||'').trim();if(!from)return{ok:false,error:'Session utilisateur invalide.'};if(!to)return{ok:false,error:'Destinataire introuvable.'};if(!text)return{ok:false,error:'Message vide.'};if(text.length>4000)return{ok:false,error:'Message trop long.'};const m={id:Utilities.getUuid(),senderId:String(from.id),recipientId:String(to.id),text:text,createdAt:new Date().toISOString(),readAt:''};msgSheet_().appendRow([m.id,m.senderId,m.recipientId,m.text,m.createdAt,m.readAt]);try{if(typeof createNotification_==='function')createNotification_({userId:String(to.id),title:'Nouveau message de '+[from.firstName,from.lastName].filter(Boolean).join(' '),message:text.slice(0,180),type:'message',url:APP_URL})}catch(_){}return{ok:true,message:m}}
function listInternalMessages_(b){const me=msgUser_(b.userId),peer=msgUser_(b.peerId);if(!me)return{ok:false,error:'Session utilisateur invalide.'};if(!peer)return{ok:false,error:'Correspondant introuvable.'};const uid=String(me.id),pid=String(peer.id),rows=msgRows_().filter(m=>(m.senderId===uid&&m.recipientId===pid)||(m.senderId===pid&&m.recipientId===uid)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(-500);const sh=msgSheet_(),all=sh.getDataRange().getValues(),now=new Date().toISOString();for(let i=1;i<all.length;i++)if(String(all[i][1])===pid&&String(all[i][2])===uid&&!String(all[i][5]||''))sh.getRange(i+1,6).setValue(now);return{ok:true,messages:rows}}
function listInternalConversations_(b){const me=msgUser_(b.userId);if(!me)return{ok:false,error:'Session utilisateur invalide.'};const uid=String(me.id),map={};msgRows_().filter(m=>m.senderId===uid||m.recipientId===uid).forEach(m=>{const other=m.senderId===uid?m.recipientId:m.senderId,old=map[other];if(!old||String(m.createdAt)>String(old.updatedAt))map[other]={otherUserId:other,lastMessage:m.text,updatedAt:m.createdAt,unread:0};if(m.recipientId===uid&&!m.readAt)map[other].unread=(map[other].unread||0)+1});return{ok:true,conversations:Object.values(map).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}}
function messagingRoutePost_(b){if(b.action==='sendInternalMessage')return sendInternalMessage_(b);if(b.action==='listInternalMessages')return listInternalMessages_(b);if(b.action==='listInternalConversations')return listInternalConversations_(b);return null}
function initialiserMessagerie(){msgSheet_();return 'Messagerie initialisée';}