// Sorties.gs — base commune Google Sheets + synchronisation automatique HelloAsso
const SORTIES_SHEET='Sorties';
const SORTIES_PARTICIPANTS_SHEET='Sorties participants';
const SORTIES_HISTORY_SHEET='Historique sorties';
const SORTIES_SYNC_PROP='HELLOASSO_SORTIES_LAST_SYNC';
const SORTIES_TRIGGER_FN='synchroniserHelloAssoSorties';

function sortiesSheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(SORTIES_SHEET);if(!sh)sh=ss.insertSheet(SORTIES_SHEET);const h=['id','title','date','location','source','pricing','notes','helloassoFormId','helloassoFormSlug','helloassoState','createdAt','updatedAt'];if(sh.getLastRow()===0)sh.appendRow(h);return sh}
function sortiesParticipantsSheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(SORTIES_PARTICIPANTS_SHEET);if(!sh)sh=ss.insertSheet(SORTIES_PARTICIPANTS_SHEET);const h=['id','sortieId','firstName','lastName','email','phone','address','source','paid','places','present','presentAt','helloassoItemId','helloassoOrderId','qrCode','createdAt','updatedAt'];if(sh.getLastRow()===0)sh.appendRow(h);return sh}
function sortiesHistorySheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(SORTIES_HISTORY_SHEET);if(!sh)sh=ss.insertSheet(SORTIES_HISTORY_SHEET);if(sh.getLastRow()===0)sh.appendRow(['id','sortieId','date','label']);return sh}
function sortiesRows_(){const v=sortiesSheet_().getDataRange().getValues();return v.length<2?[]:v.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),title:String(r[1]||''),date:String(r[2]||''),location:String(r[3]||''),source:String(r[4]||''),pricing:String(r[5]||''),notes:String(r[6]||''),helloassoFormId:String(r[7]||''),helloassoFormSlug:String(r[8]||''),helloassoState:String(r[9]||''),createdAt:String(r[10]||''),updatedAt:String(r[11]||'')}))}
function sortiesParticipantsRows_(){const v=sortiesParticipantsSheet_().getDataRange().getValues();return v.length<2?[]:v.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),sortieId:String(r[1]),firstName:String(r[2]||''),lastName:String(r[3]||''),email:String(r[4]||''),phone:String(r[5]||''),address:String(r[6]||''),source:String(r[7]||''),paid:String(r[8]).toLowerCase()==='true',places:Number(r[9]||1),present:String(r[10]).toLowerCase()==='true',presentAt:String(r[11]||''),helloassoItemId:String(r[12]||''),helloassoOrderId:String(r[13]||''),qrCode:String(r[14]||''),createdAt:String(r[15]||''),updatedAt:String(r[16]||'')}))}
function sortiesHistoryRows_(){const v=sortiesHistorySheet_().getDataRange().getValues();return v.length<2?[]:v.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),sortieId:String(r[1]),date:String(r[2]||''),label:String(r[3]||'')}))}
function sortiesLastSync_(){return PropertiesService.getScriptProperties().getProperty(SORTIES_SYNC_PROP)||''}
function sortiesAdminList_(){const ps=sortiesParticipantsRows_(),hs=sortiesHistoryRows_();return{ok:true,lastHelloAssoSync:sortiesLastSync_(),sorties:sortiesRows_().map(s=>({...s,localOnly:false,participants:ps.filter(p=>p.sortieId===s.id),history:hs.filter(h=>h.sortieId===s.id)}))}}
function sortiesHistoryAdd_(sortieId,label){sortiesHistorySheet_().appendRow([Utilities.getUuid(),sortieId,new Date().toISOString(),label])}
function sortiesFindRow_(id){const sh=sortiesSheet_(),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id))return{sh:sh,row:i+1,values:v[i]};return null}
function sortiesParticipantFindRow_(id){const sh=sortiesParticipantsSheet_(),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(id))return{sh:sh,row:i+1,values:v[i]};return null}

function sortiesAdminSave_(s){s=s||{};const now=new Date().toISOString(),id=String(s.id||Utilities.getUuid()),found=sortiesFindRow_(id);const old=found&&found.values||[];const row=[id,String(s.title||old[1]||'').trim(),String(s.date||old[2]||''),String(s.location||old[3]||'').trim(),String(s.source||old[4]||'Manuelle'),String(s.pricing||old[5]||'free'),String(s.notes||old[6]||''),String(s.helloassoFormId||old[7]||''),String(s.helloassoFormSlug||old[8]||''),String(s.helloassoState||old[9]||''),String(old[10]||now),now];if(!row[1])return{ok:false,error:'Titre manquant'};if(found)found.sh.getRange(found.row,1,1,row.length).setValues([row]);else sortiesSheet_().appendRow(row);sortiesHistoryAdd_(id,found?'Sortie modifiée':'Sortie créée manuellement');return{ok:true,sortie:sortiesAdminList_().sorties.find(x=>x.id===id)}}
function sortiesAdminDelete_(id){const f=sortiesFindRow_(id);if(!f)return{ok:false,error:'Sortie introuvable'};const psh=sortiesParticipantsSheet_(),pv=psh.getDataRange().getValues();for(let i=pv.length-1;i>=1;i--)if(String(pv[i][1])===String(id))psh.deleteRow(i+1);const hsh=sortiesHistorySheet_(),hv=hsh.getDataRange().getValues();for(let i=hv.length-1;i>=1;i--)if(String(hv[i][1])===String(id))hsh.deleteRow(i+1);f.sh.deleteRow(f.row);return{ok:true}}
function sortiesAdminSaveParticipant_(p){p=p||{};if(!p.sortieId)return{ok:false,error:'Sortie manquante'};const now=new Date().toISOString(),id=String(p.id||Utilities.getUuid()),found=sortiesParticipantFindRow_(id),old=found&&found.values||[];const row=[id,String(p.sortieId),String(p.firstName||old[2]||'').trim(),String(p.lastName||old[3]||'').trim(),String(p.email||old[4]||'').trim().toLowerCase(),String(p.phone||old[5]||'').trim(),String(p.address||old[6]||'').trim(),String(p.source||old[7]||'Manuelle'),p.paid===true||String(p.paid).toLowerCase()==='true',Math.max(1,Number(p.places||old[9]||1)),p.present===true||String(p.present).toLowerCase()==='true',String(p.presentAt||old[11]||''),String(p.helloassoItemId||old[12]||''),String(p.helloassoOrderId||old[13]||''),String(p.qrCode||old[14]||''),String(old[15]||now),now];const existing=sortiesParticipantsRows_().find(x=>x.sortieId===row[1]&&x.id!==id&&((row[4]&&x.email.toLowerCase()===row[4])||(row[5]&&x.phone===row[5])||(row[2]&&row[3]&&String(x.firstName).toLowerCase()===row[2].toLowerCase()&&String(x.lastName).toLowerCase()===row[3].toLowerCase())));if(existing)return{ok:false,error:'Ce participant est déjà inscrit à cette sortie.',duplicateId:existing.id};if(found)found.sh.getRange(found.row,1,1,row.length).setValues([row]);else sortiesParticipantsSheet_().appendRow(row);sortiesHistoryAdd_(row[1],found?'Participant modifié':'Participant ajouté : '+[row[2],row[3]].filter(Boolean).join(' '));return{ok:true,participant:sortiesParticipantsRows_().find(x=>x.id===id)}}
function sortiesAdminDeleteParticipant_(id){const f=sortiesParticipantFindRow_(id);if(!f)return{ok:false,error:'Participant introuvable'};const sortieId=String(f.values[1]),name=[f.values[2],f.values[3]].filter(Boolean).join(' ');f.sh.deleteRow(f.row);sortiesHistoryAdd_(sortieId,'Participant retiré : '+name);return{ok:true}}
function sortiesAdminCheckTicket_(sortieId,code){code=String(code||'').trim();if(!code)return{ok:false,error:'Code vide'};const ps=sortiesParticipantsRows_(),p=ps.find(x=>x.sortieId===String(sortieId)&&(String(x.qrCode)===code||String(x.helloassoItemId)===code||String(x.id)===code));if(!p)return{ok:false,valid:false,error:'Billet inconnu'};if(p.present)return{ok:true,valid:false,alreadyUsed:true,participant:p,error:'Billet déjà utilisé'};const f=sortiesParticipantFindRow_(p.id),now=new Date().toISOString();f.sh.getRange(f.row,11).setValue(true);f.sh.getRange(f.row,12).setValue(now);f.sh.getRange(f.row,17).setValue(now);sortiesHistoryAdd_(sortieId,'Présence validée : '+[p.firstName,p.lastName].filter(Boolean).join(' '));p.present=true;p.presentAt=now;return{ok:true,valid:true,participant:p}}

function sortiesFormDate_(f){return String(f.startDate||f.eventStartDate||f.date||f.meta&&f.meta.createdAt||'')}
function sortiesFormLocation_(f){const a=f.place||f.location||{};return String(a.name||a.address||f.city||'').trim()}
function sortiesUpsertForm_(f){const sh=sortiesSheet_(),rows=sh.getDataRange().getValues(),slug=String(f.formSlug||f.slug||''),fid=String(f.formId||f.id||''),now=new Date().toISOString();for(let i=1;i<rows.length;i++){if((fid&&String(rows[i][7])===fid)||(slug&&String(rows[i][8])===slug)){sh.getRange(i+1,2,1,11).setValues([[String(f.title||f.name||rows[i][1]||'Sortie HelloAsso'),sortiesFormDate_(f)||String(rows[i][2]||''),sortiesFormLocation_(f)||String(rows[i][3]||''),'HelloAsso',String(rows[i][5]||'paid'),String(f.description||rows[i][6]||''),fid,slug,String(f.state||''),String(rows[i][10]||now),now]]);return{id:String(rows[i][0]),created:false}}}const id=Utilities.getUuid();sh.appendRow([id,String(f.title||f.name||'Sortie HelloAsso'),sortiesFormDate_(f),sortiesFormLocation_(f),'HelloAsso','paid',String(f.description||''),fid,slug,String(f.state||''),now,now]);sortiesHistoryAdd_(id,'Sortie créée automatiquement depuis HelloAsso');if(typeof createNotification_==='function')createNotification_({type:'helloasso-sortie',title:'Nouvelle sortie HelloAsso',message:String(f.title||f.name||'Une nouvelle sortie')+' a été ajoutée automatiquement.',targetPermissions:['sorties','superadmin'],data:{view:'sorties',sortieId:id,helloassoFormSlug:slug}});return{id:id,created:true}}
function sortiesParticipantFromItem_(sortieId,order,item,detail){detail=detail||{};const payer=order.payer||{},user=detail.user||item.user||{};const first=String(user.firstName||payer.firstName||'').trim(),last=String(user.lastName||payer.lastName||'').trim(),email=String(user.email||payer.email||'').trim().toLowerCase(),phone=String((payer.phone||payer.phoneNumber)||'').trim(),addr=[payer.address,payer.zipCode,payer.city].filter(Boolean).join(' '),qr=String(detail.qrCode||item.qrCode||'');return{sortieId:sortieId,firstName:first,lastName:last,email:email,phone:phone,address:addr,source:'HelloAsso',paid:true,places:1,present:false,presentAt:'',helloassoItemId:String(item.id||''),helloassoOrderId:String(order.id||''),qrCode:qr}}
function sortiesUpsertParticipant_(p){const sh=sortiesParticipantsSheet_(),rows=sh.getDataRange().getValues(),now=new Date().toISOString();for(let i=1;i<rows.length;i++){if((p.helloassoItemId&&String(rows[i][12])===p.helloassoItemId)||(String(rows[i][1])===p.sortieId&&p.email&&String(rows[i][4]).toLowerCase()===p.email.toLowerCase())){const id=String(rows[i][0]);sh.getRange(i+1,2,1,16).setValues([[p.sortieId,p.firstName,p.lastName,p.email,p.phone,p.address,p.source,!!p.paid,Number(p.places||1),String(rows[i][10]).toLowerCase()==='true',String(rows[i][11]||''),p.helloassoItemId,p.helloassoOrderId,p.qrCode,String(rows[i][15]||now),now]]);return{id:id,created:false}}}const id=Utilities.getUuid();sh.appendRow([id,p.sortieId,p.firstName,p.lastName,p.email,p.phone,p.address,p.source,!!p.paid,Number(p.places||1),false,'',p.helloassoItemId,p.helloassoOrderId,p.qrCode,now,now]);sortiesHistoryAdd_(p.sortieId,'Inscription HelloAsso ajoutée : '+[p.firstName,p.lastName].filter(Boolean).join(' '));return{id:id,created:true}}
function synchroniserHelloAssoSorties(){const lock=LockService.getScriptLock();if(!lock.tryLock(1000))return{ok:true,skipped:true};try{const cfg=helloAssoConfig_();if(!cfg.ok)return cfg;let created=0,updated=0,participantsCreated=0,formsSeen=0,page=1,continuation='';do{const params={pageIndex:page,pageSize:100,formTypes:'Event'};if(continuation)params.continuationToken=continuation;const j=helloAssoGet_('/organizations/'+encodeURIComponent(cfg.orgSlug)+'/forms',params),forms=Array.isArray(j.data)?j.data:(Array.isArray(j.items)?j.items:[]);forms.forEach(f=>{formsSeen++;const sr=sortiesUpsertForm_(f);sr.created?created++:updated++;const slug=String(f.formSlug||f.slug||'');if(!slug)return;let op=1,oc='';do{const opm={pageIndex:op,pageSize:100};if(oc)opm.continuationToken=oc;const oj=helloAssoGet_('/organizations/'+encodeURIComponent(cfg.orgSlug)+'/forms/Event/'+encodeURIComponent(slug)+'/orders',opm),orders=Array.isArray(oj.data)?oj.data:(Array.isArray(oj.items)?oj.items:[]);orders.forEach(order=>(order.items||[]).filter(item=>String(item.state||'').toLowerCase()!=='canceled'&&String(item.state||'').toLowerCase()!=='refunded').forEach(item=>{let detail=item;try{detail=helloAssoGet_('/items/'+encodeURIComponent(item.id),{withDetails:'true'})}catch(_){}const pr=sortiesUpsertParticipant_(sortiesParticipantFromItem_(sr.id,order,item,detail));if(pr.created)participantsCreated++}));oc=String(oj.pagination&&oj.pagination.continuationToken||oj.continuationToken||'');op++;if(!oc&&orders.length<100)break}while(op<=30)});continuation=String(j.pagination&&j.pagination.continuationToken||j.continuationToken||'');page++;if(!continuation&&forms.length<100)break}while(page<=20);PropertiesService.getScriptProperties().setProperty(SORTIES_SYNC_PROP,new Date().toISOString());return{ok:true,formsSeen:formsSeen,created:created,updated:updated,participantsCreated:participantsCreated,lastHelloAssoSync:sortiesLastSync_()}}finally{lock.releaseLock()}}
function sortiesAdminSync_(){return synchroniserHelloAssoSorties()}
function installerHelloAssoSortiesSync(){const cfg=helloAssoConfig_();if(!cfg.ok)throw new Error(cfg.error);ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()===SORTIES_TRIGGER_FN).forEach(t=>ScriptApp.deleteTrigger(t));ScriptApp.newTrigger(SORTIES_TRIGGER_FN).timeBased().everyMinutes(5).create();return synchroniserHelloAssoSorties()}
